### ISSUE TITLE
Adding better documentation for modding with this engine

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#1]
First off, it's great that qfusion is adopting a more open development style with this repository here on Github. The new features are also quite impressive.

Now the issue is that besides some very fragmented and partially outdated documentation on the warsow forums and wiki there is hardly any details on how to make a game with this engine.

The first step would be probably to include a feature readme in this repository.

Additionally it would be great if an editing & scripting wiki could be set up. I would help to compile as much of the scattered information from various Warsow sources in it, but obviously there would be a need to double check and update it to reflect the most up to date features of the engine.

It is actually a pity that qfusion is so relatively unknown, and IMHO that is due to a lack of documentation and an overview on the features etc.

**Comment by viciious** [comment]
Yeah, I do have to agree here, proper documentation has always been a problem. However it's often the case with hobby-driven projects with one person backing: I simply have too little time and motivation to handle everything. Any help in this regards would be highly appreciated :)

**Comment by poVoq** [comment]
Great, I see that you activated the wiki on this page. I will start transferring various tutorials and the not outdated wiki content from the Warsow page then.

Edit: hmm when I click on the wiki link above it just throws me back to the code page. Maybe you need to at least add a cover page? Also do I need permission to be able to edit the wiki? If so, please configure it accordingly.

**Comment by poVoq** [comment]
Ok, thanks the wiki works now and I started filling it with some stuff from the warsow wiki and the forums. Still a lot to do though ;) Any help is appreciated, especially in the "developers" section with deals with the qfusion engine itself, which seems to be largely undocumented.

**Comment by learn-more** [comment]
how about doxygen?

**Comment by viciious** [comment]
Patches welcome ;)
