### ISSUE TITLE
Reimplement bloom

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#10]
The old bloom code dating back to 2007 is gone but nothing has yet been implemented as the replacement for it. Bloom and/or HDR is pretty much a must-have feature for any modern engine so this is a blocking issue for the next release.

**Comment by poVoq** [comment]
Have a look at the SuperTuxKart repository. They have recently implemented selectiv bloom, god-rays, a special shadow-mapping technique etc. and are also running on an GLSL renderer. See some examples here:
http://supertuxkart.blogspot.com/

I guess this is the needed directory: http://sourceforge.net/p/supertuxkart/code/13449/tree/main/branches/cand/midterm/data/shaders/

**Comment by dnk777** [comment]
Does it support at least floating-point rendertargets?

**Comment by viciious** [comment]
It?

**Comment by dnk777** [comment]
I mean Qfusion

**Comment by viciious** [comment]
No

**Comment by viciious** [comment]
Done. And it only took me three years to fix this..

5191827e8a3efa186416641664e3635930428318
