### ISSUE TITLE
Os X: vid_fullscreen value change causes problems

### ISSUE THREAD

**Issue by crustyftw** [Qfusion/qfusion#100]
When you change vid_fullscreen from 0 to 1 or from 1 to 0 warsow become unplayable or in some screen becomes black and stuck. Found on os x 10.8.
I will add more details asap

**Comment by viciious** [comment]
Андрей, это Вам :)

**Comment by vkni** [comment]
Спасибо, я уже прочёл в ПМ на warsow.net.

**Comment by vkni** [comment]
Таки нужно, чтобы после vid_fullscreen вызывался vid_restart. 

Виктор, как это лучше всего сделать? Если из меню включать/выключать полноэкранный режим, vid_restart автоматом выполняется. А вот из командной строки вызов vid_fullscreen X не тянет автоматом vid_restart (по крайней мере под OSX).

**Comment by viciious** [comment]
vid_fullscreen надо регистрировать с CVAR_LATCH_VIDEO

31 мая 2014 г., 6:08 пользователь Vkni notifications@github.com написал:

> Таки нужно, чтобы после vid_fullscreen вызывался vid_restart.
> 
> Виктор, как это лучше всего сделать? Если из меню включать/выключать
> полноэкранный режим, vid_restart автоматом выполняется. А вот из командной
> строки вызов vid_fullscreen X не тянет автоматом vid_restart (по крайней
> мере под OSX).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/issues/100#issuecomment-44715440.

## 

Best regards,
 Victor Luchitz

**Comment by vkni** [comment]
Now everything works at least for me. (it says, that you need vid_restart)

**Comment by crustyftw** [comment]
So it's just a workaround, right?

**Comment by viciious** [comment]
Sort of, yes.

2014-06-04 13:56 GMT+04:00 crustyftw notifications@github.com:

> So it's just a workaround, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/issues/100#issuecomment-45072292.

## 

Best regards,
 Victor Luchitz
