### ISSUE TITLE
XError  - 155 (GLX) 5 (X_GLXMakeCurrent)

### ISSUE THREAD

**Issue by vkni** [Qfusion/qfusion#102]
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  221
  Current serial number in output stream:  221

**Comment by vkni** [comment]
I get this at every QFusion run.

**Comment by viciious** [comment]
Works for me

**Comment by viciious** [comment]
Please try pulling from master

2014-05-31 8:13 GMT+04:00 Vkni notifications@github.com:

> I get this at every QFusion run.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/issues/102#issuecomment-44717473.

## 

Best regards,
 Victor Luchitz

**Comment by vkni** [comment]
Thanks, it works. The X Error dissapeared.
