### ISSUE TITLE
New QFusion icon

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#103]
Current max resolution QFusion icon is 48x48:
![qfusion_demo-8](https://cloud.githubusercontent.com/assets/24836/3148516/6aa6b882-ea61-11e3-8628-1ddb38177d98.png)
We need a new beautiful hi-res icon

**Comment by vkni** [comment]
Красивый Серп-и-Молот. :-)

Даже непонятно, как его перечерчивать-то. Может не выпендриваться, а сразу с флага скопировать? (шутка)

**Comment by Triang3l** [comment]
Сломанный серп и гвоздь =)

**Comment by Vectory** [comment]
Tut for future reference: https://imgur.com/gallery/xL0Ba
because I dont have the diskspace to install inkscape, at the moment.

**Comment by Triang3l** [comment]
Also a 192x192 icon would be nice for #3 :)

**Comment by klevap** [comment]
you can use this one 
![bitmap_3](https://cloud.githubusercontent.com/assets/6583882/4300950/182b0a8a-3e4a-11e4-8d39-f3f302a8a478.png)

**Comment by adem4ik** [comment]
extone i guess you should make pull request instead, but ye, good job :+1:

**Comment by klevap** [comment]
this would require to properly convert .png to .xpm and multires .ico files, something what I did not like last time =)

**Comment by Triang3l** [comment]
Awesome work :)

**Comment by adem4ik** [comment]
I've updated icons for Windows and Linux by extone's one. Here is how it looks on Lin.
![wsw](https://cloud.githubusercontent.com/assets/4707112/4438519/184cc01e-47ad-11e4-8691-abfff4b8d336.png)
