### ISSUE TITLE
Two (A bit crazy, I guess) enhancement ideas

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#11]
Ok, I guess both are unlikely to get implemented, but I wanted to throw them out here:
1. Port the in-game level editor, the terrain and the bullet physics (and what ever else seems cool) from the Quake2 based Ya3dag engine: http://www.moddb.com/mods/r-reinhard/downloads/ya3dag-v142-source-code
2. (and this is rather for an experiment in a cool art-style) Expand the sprite code to allow for multi-directional sprites that can be animated. The animations should be possible to be influenced by player input and the sprites need to support full multi-texturing (normal-maps etc.). What I actually would like to do is to create character "models" a bit like those back in the Doom/Duke3D times with that, but utilizing modern techniques like mouse driven upper body and head (through md3 tags or bone animation blending) and normal-mapped (pre-rendered) sprites. These kind of advanced spriting tech is already quite successfully used in modern 2D engines (including isometric games) and one could probably make a quite cool and pseudo retro looking 3D game that way. As a side effect, creating new player characters or changing the look of them will be much quicker and simpler to do.

Well, tell me what you think about that ;)

**Comment by viciious** [comment]
I think you're going overboard with this :)

**Comment by poVoq** [comment]
A shame... but did you ever look at the ya3dag code, to determine how compatible it is? I actually also asked the creator of that engine how difficult it would be to port some of the really nice features from qfusion ;) But he seems to ignore me so far :( And besides... no Linux port...
