### ISSUE TITLE
[BUG] Some textures are not displayed

### ISSUE THREAD

**Issue by klevap** [Qfusion/qfusion#118]
On some maps some textures as well as all hit decals are not displayed. When decal on wall should appear console prints error message:
^3Failed to compile vertex shader for program defaultQ3AShader_cc_ac_dl4_ls3
ERROR: 19:9: 'a_LightmapCoord01' : syntax error syntax error

bug seems to appear after commit c029ea2 "Pack lightmap coordinates into two vertex attributes" (25 April)
Happens e.g. on following map https://dl.dropboxusercontent.com/u/102271334/zenith.bsp

**Comment by viciious** [comment]
Make sure your Glsl scripts in basewsw are up to date

**Comment by klevap** [comment]
ok, tried it again
that's what i've done:

1) downloaded and unpacked warsow_1.51_unified.tar.gz
2) removed executables and 'libs' folder
3) upacked dataXXX.pk3 files in 'basewsw' folder
4) removed dataXXX.pk3 and modulesXXX.pk3 files
5) removed 'glsl' folder in 'basewsw' folder
6) renamed 'basewsw' to 'base'
7) downloaded https://github.com/viciious/qfusion/archive/master.zip
8) rebuild in vs2013express
9) copied executables, 'libs' and 'base' folders into root folder from Release/x86 folder
10) copied 'glsl' folder from 'qfusion-master' folder to 'base' folder
11) copied https://dl.dropboxusercontent.com/u/102271334/zenith.bsp into 'base/maps' folder
12) run qfusion_x86.exe
13) run from console 'map zenith' - bug still here
14) condump https://dl.dropboxusercontent.com/u/102271334/condump.txt
15) screenshot https://dl.dropboxusercontent.com/u/102271334/wsw_140917_182504.jpg

**Comment by klevap** [comment]
and this is how it should look (wsw 1.51)
https://dl.dropboxusercontent.com/u/102271334/wsw_140917_183354.jpg

**Comment by Triang3l** [comment]
Fixed the bug, qf_lmvec01 was undefined for 3 and 4 lightstyles.

Regarding the HUD textures: we optimized the loading screen and number font rendering, so we had to add some new files to the game. I uploaded the files required for 1.6 to work with 1.51 content: https://onedrive.live.com/redir?resid=65B4D1E61B5CD82A!1574&authkey=!AG25Vtnl1QTCZN4&ithint=folder%2c

**Comment by klevap** [comment]
Thanks a lot!
