### ISSUE TITLE
Xcode 6.01

### ISSUE THREAD

**Issue by vkni** [Qfusion/qfusion#119]
Други, давеча вышел XCode 6.0.1, и моя система предлагает обновить XCode с текущей версии 5.1.1 на неё. Насколько я знаю, кроме меня под OSX компилирует наш уважаемый Stopiccot, но может быть ещё кто-нибудь этим балуется. Есть ли у вас возражения против перехода на XCode 6.0.1 и соответствующего обновления проекта QFusion xcodeproj?

---

Same as above. Dear Friends, Xcode 6.0.1 is out. My OSX system invites me to update my current XCode 5.1.1 to this version. As far as I know there are other people who compile QFusion for OSX besides me. For instance respected Stoppicot. So, does anyone mind if I upgrade XCode and QFusion xcodeproj to 6.0.1?

**Comment by stopiccot** [comment]
Я так понимаю проблема в том, что в шестом икскоде нет base sdk для 10.8?

**Comment by stopiccot** [comment]
Но вообще давно пора переходить на Lastes SDK и выставление Deployment Target на нужную версию

**Comment by stopiccot** [comment]
И вообще надо б проект выкинуть и на cmake перейти хотя б для мака. Тогда каждый сможет генерировать проект под свою версию икскода и не будет проблем.

**Comment by vkni** [comment]
> Я так понимаю проблема в том, что в шестом икскоде нет base sdk для 10.8?

Честно говоря, не знаю. Тогда давайте не будем обновлять XCode - чем меньшую версию OSX мы поддерживаем, тем лучше.

**Comment by stopiccot** [comment]
qfusion can be built with Xcode 6 for quite a while already
