### ISSUE TITLE
FPS drop with textures with alpha channel

### ISSUE THREAD

**Issue by klevap** [Qfusion/qfusion#122]
FPS drops ~2 times when replacing used .jpg textures with the same textures in .png or .tga format.
It does not matter is map compiled before or after replacement.
This issue does not exist at "r_lighting_deluxmapping 0"

**Comment by viciious** [comment]
wtf?

2014-10-06 10:14 GMT+04:00 extone notifications@github.com:

> FPS drops ~2 times when replacing used .jpg textures with the same
> textures in .png or .tga format.
> It does not matter is map compiled before or after replacement.
> This issue does not exist at "r_lighting_deluxmapping 0"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/issues/122.

## 

Best regards,
 Victor Luchitz

**Comment by Triang3l** [comment]
What's your graphics card, and when did the issue appear for the first time?

**Comment by viciious** [comment]
What are you trying to accomplish anyway? Also, why adding an alpha
channel where it's not needed at all?

2014-10-06 11:47 GMT+04:00 SiPlus notifications@github.com:

> What's your graphics card?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viciious/qfusion/issues/122#issuecomment-57983883.

## 

Best regards,
 Victor Luchitz

**Comment by Triang3l** [comment]
Also, can you post any map where we could reproduce this?

**Comment by klevap** [comment]
did a litle bit more testing. issue presented in both wsw 1.51 and latest qfusion. issue appears when high+ video profile loaded and not presented on medium video profile.
you can test it on this map, use only jpg or png texture pack at time
https://dl.dropboxusercontent.com/u/102271334/t.pk3
https://dl.dropboxusercontent.com/u/102271334/t_jpg.pk3
https://dl.dropboxusercontent.com/u/102271334/t_png.pk3

**Comment by viciious** [comment]
Not a bug. High+ enables reliefmapping which is only applied to surfaces with normalmaps, containing an alpha channel.
