### ISSUE TITLE
Black screen while running QF with Warsow 1.03 packages on Kubuntu 13.04

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#13]
I was trying to run lastest QF with Warsow 1.03 packages on my Kubuntu 13.04. In the result I can hear sound, run any map, but without ingame screen image. Here is the console output - http://yadi.sk/d/LcDnEoPk8dJq7

My PC has such specs:
Intel i5 2320 Sandy Bridge, 8GB RAM, Nvidia GTX 650 1GB RAM.

As a side note, I have xorg-edgers' ppa included to get latest beta Nvidia driver 325.15 - http://www.nvidia.com/object/linux-display-amd64-325.15-driver.html I don't think it is the reason of the problem, since Warsow 1.03 and Dota 2 run perfectly without any graphics glitches.

Originally I've started discussion on warsow.net forum - http://www.warsow.net/forum/thread/t/219987#post-219987 . Also there was a temporary fix for the Black Screen, but I guess it turns off a lot of graphics features:

""#version 120\n" \
"#extension GL_EXT_draw_instanced : enable\n"

made it work for me. Not sure if that is the proper way though.
I still got some shader error in-game. "

**Comment by Hamcha** [comment]
Same thing on Windows

**Comment by viciious** [comment]
Please try the latest git version

2013/9/4 Hamcha notifications@github.com

> Same thing on Windows
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/13#issuecomment-23802274
> .

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
it works now! :+1: But there is some graphics glitches which look like missing textures. (same thing was before while using patch from hettoo)
![wsw_130905_001241](https://f.cloud.github.com/assets/4707112/1083703/1d32371c-159f-11e3-9ba0-1badfcfa01e6.jpg)
![wsw_130905_001304](https://f.cloud.github.com/assets/4707112/1083704/1d52458e-159f-11e3-858a-08543b754c61.jpg)
Also I like that effect when picked Item looks transparent until it spawns. or mb it is a glitch too...
![wsw_130905_001215](https://f.cloud.github.com/assets/4707112/1083707/42eba3ee-159f-11e3-9c79-aa83ed2ed7f4.jpg)
Console output if you need it -> http://yadi.sk/d/5_3H6jHz8jKTi

**Comment by viciious** [comment]
I think the missing textures are caused by warsow 1.03 using the 'cellshade' shader command which has been renamed to 'celshade' in 1.1

And no, the transparency effect isn't a glitch, it's a feature.

Closing the original issue.

**Comment by viciious** [comment]
More logs here: http://yadi.sk/d/MfCFOcKM9mce7

**Comment by hettoo** [comment]
https://github.com/viciious/qfusion/commit/902fe10ff1b448f0f0af285f6fecacbfb4e7de87#L0R1389
QF_GLSL_VERSION or QF_GLSLVERSION?
^^

**Comment by viciious** [comment]
Should be QF_GLSL_VERSION idd

2013/9/24 Gerco van Heerdt notifications@github.com

> 902fe10#L0R1389https://github.com/viciious/qfusion/commit/902fe10ff1b448f0f0af285f6fecacbfb4e7de87#L0R1389
> QF_GLSL_VERSION or QF_GLSLVERSION?
> ^^
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/13#issuecomment-24954073
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
Well, it used to be QF_GLSLVERSION, so I guess this should have been renamed too: https://github.com/viciious/qfusion/blob/902fe10ff1b448f0f0af285f6fecacbfb4e7de87/source/ref_gl/r_program.c#L755
Either way, re-fixes the black screen. :)

**Comment by viciious** [comment]
Fixed
