### ISSUE TITLE
[AI] Bot doesn't check if the item was picked

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#133]
Bot doesn't check if the item was picked while he was on his way to this item. I'm sure it is not particular case, I saw much of such bot moves. The logic seems following to me:
1) Bot A should have this item on his path
2) Item was picked by another player/bot before bot A riched this spot.
3) Bot A still goes to this spot even if there is no such item anymore.

Video: http://youtu.be/7CriZyfNJ4M.
Wsw 1.5 Demo: https://www.mediafire.com/?mstyd46eu34wp00 (moment at 8:35, Lobita picked YA, while Porkalator didn't care about it and came to YA spot too)

**Comment by viciious** [comment]
I'm not sure what to make out of this video. Can you tell me what's going
on there?

2015-01-07 13:35 GMT+03:00 Andrei Stepanov <notifications@github.com>:

> Bot doesn't check if the item was picked while he was on his way to this
> item. I'm sure it is not particular case, I saw much of such bot moves. The
> logic seems following to me:
> 1) Bot A should have this item on his path
> 2) Item was picked by another player/bot before bot A riched this spot.
> 3) Bot A still goes to this spot even if there is no such item anymore.
>
> Video: http://youtu.be/7CriZyfNJ4M.
> Wsw 1.6 Demo: (moment at 8:35, Lobita picked YA, while Porkalator didn't
> care about it and came to YA spot too)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Warsow/qfusion/issues/133>.
>



-- 
Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Is the bug still present in Warsow 2.0?

**Comment by adem4ik** [comment]
can't reproduce now, fixed
