### ISSUE TITLE
[AI] Bot can cycle on the same path

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#134]
Bot can cycle on the same path if he fails to reach one of the spots on his way. Here is how it looks on the following example on wdm6: RA -> EB -> RL (where bot fails) -> so he decides to repeat it once more - > RA... I'm sure it is not particular case, since I saw the same bot cycle on other maps.

Video: http://youtu.be/iUNFwoNBkmo
Wsw 1.5 Demo: https://www.mediafire.com/?ai1cnq69imn2tdu

**Comment by viciious** [comment]
The video is marked as private.

2015-01-07 13:43 GMT+03:00 Andrei Stepanov notifications@github.com:

> Bot can cycle on the same path if he fails to reach one of the spots on
> his way. Here is how it looks on the following example on wdm6: RA -> EB ->
> RL (where bot fails) -> so he decides to repeat it once more - > RA... I'm
> sure it is not particular case, since I saw the same bot cycle on other
> maps.
> 
> Video: http://youtu.be/iUNFwoNBkmo
> Wsw 1.5 Demo: https://www.mediafire.com/?ai1cnq69imn2tdu
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/134.

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
video is fixed now

**Comment by adem4ik** [comment]
can't reproduce now, fixed
