### ISSUE TITLE
Image loading code question.

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#139]
Don't know where to ask. So I decided to create an issue.

I'm currently investigating if SDL2_image can be used for loading textures in qfusion. While I was digging into current image loading code I found one thing that bothers me.

In `R_LoadImageFromDisk` function after image data was loaded into memory it's uploaded to GPU using `R_Upload32` function. But I can find where texture data is being freed from CPU memory after upload. I am missing something or textures are really staying in CPU memory till app is closed?

**Comment by viciious** [comment]
All textures are loaded into single persistent resampling buffer, one per context. So yes, one texture is always residing in RAM.

**Comment by viciious** [comment]
https://github.com/Warsow/qfusion/blob/master/source/ref_gl/r_image.c#L399

**Comment by stopiccot** [comment]
I've pushed SDL2_image branch. And I need kind of advice\opinion here:

https://github.com/Warsow/qfusion/blob/SDL2_image/source/ref_gl/r_imagelib.c#L996

Of course I can allocate same memory block by passed `allocbuf` function, copy data from SDL surface to it and free SDL memory chunk. But I want to avoid this useless memory copy. Any thoughts? Or it is not such a big deal and memcpy is fine?

**Comment by viciious** [comment]
I think that loading images via SDL_image isn't such a good idea in the first place

**Comment by viciious** [comment]
We have a fixed number of supported image types

**Comment by stopiccot** [comment]
Main idea of using SDL2_image is to get free from maintaining libjpeg, libpng and ownwritten ptx loading code.

**Comment by stopiccot** [comment]
Let other people to do this maintenance for you.

**Comment by viciious** [comment]
Ideally, we should avoid useless memcpy calls.

Btw, images loading alone isn't sufficent to drop libs maintanance. The writing codes should be rewritten as well.

**Comment by stopiccot** [comment]
Yeah, it's work in progress so no writing yet. Just wanted to ask how to deal with this memory allocation issue.

**Comment by viciious** [comment]
It appears that without interefering with the current design, memcpy is the
only option you have there.

2015-01-21 17:46 GMT+03:00 Alexey notifications@github.com:

> Yeah, it's work in progress so no writing yet. Just wanted to ask how to
> deal with this memory allocation issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/139#issuecomment-70849182.

## 

Best regards,
 Victor Luchitz
