### ISSUE TITLE
Inconsistent license text

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#141]
Some files have "Chasseur de bots" license, some "Id software" license, some don't have  any at all. I think we should kinda unify it.

**Comment by viciious** [comment]
Why is it important at all? Besides, original id soft files still have the original license.

**Comment by stopiccot** [comment]
It's obviously not the most important thing in the world. Just look messy to see different license headers across files.

**Comment by viciious** [comment]
Closing this as unimportant.
