### ISSUE TITLE
Switch to cmake

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#142]
OS X build seems to be fine so I really want to remove source/Makefile too. Please post here anything that prevents from switching to cmake in your opinion so i can fix it.

**Comment by viciious** [comment]
Haven't yet tried cmake withour priv repo and buildbot

**Comment by stopiccot** [comment]
Looking forward for you to try it and provide some feedback.

priv repo?

**Comment by viciious** [comment]
Obviously we're not using this public github repo for media files or building the official binaries.

**Comment by stopiccot** [comment]
priv was for private, didn't get that first time

**Comment by stopiccot** [comment]
Still, please give it a try when you have time

**Comment by adem4ik** [comment]
![cmake_vs_make](https://cloud.githubusercontent.com/assets/4707112/5888555/ced776da-a414-11e4-8a52-7baf468711b6.png)
1) cmake doesn't make bash scripts for binaries
2) somehow cmake provide the name for main binary with upper case symbols: QFusion vs qfusion. it is not so important but still :baby_chick: 
3) cmake release files are bigger than make's files. (11.7 MB vs 9 MB)

**Comment by stopiccot** [comment]
1) Btw, why they a actually needed?
2) It was intended to unify binary name across all platforms and for now I sticked to "QFusion". Of course I can change it to "qfusion".
3) This should be probably investigated. Seems to be some difference in compile\link flags.

**Comment by Triang3l** [comment]
It's "Qfusion" anyway, not "QFusion".

**Comment by sundflux** [comment]
Bash scripts are for launching the game with same executable on any architecture and for having env vars for some settings, like whether or not use profile dir or not. Iirc these are very much static, so these can be just copied over when needed.

For the binary name, please keep it lowercase.

**Comment by stopiccot** [comment]
Any specific reasons for lowercase binary?

**Comment by sundflux** [comment]
Linux.

**Comment by stopiccot** [comment]
Em.. can you elaborate on this?

**Comment by sundflux** [comment]
It's general convetion to use lowercase binaries, and unlike OS X, Linux filesystems are really case sensitive, not only case-aware like hfs on OS X.

**Comment by viciious** [comment]
+1 to what @sundflux just said

**Comment by stopiccot** [comment]
Linux binary name should be lowercase after commit c4009f237b30b6d4adedc2031cec217f0ea180a8

**Comment by viciious** [comment]
We need to make sure that cmake-produced bins are equivalent to the "old"
bins in terms of compilation and optimization settings.

вторник, 3 февраля 2015 г. пользователь Alexey написал:

> Linux binary name should be lowercase after commit c4009f2
> https://github.com/Warsow/qfusion/commit/c4009f237b30b6d4adedc2031cec217f0ea180a8
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/142#issuecomment-72596060.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Yeah, that's should be investigated. Because cmake uses same flags, but binary size is different for some reason. Maybe something is missing. I'll compare handcrafted and generated makefiles carefull when i get time.

**Comment by stopiccot** [comment]
Found first one. By default cmake uses `-O3` for release builds compared to qfusions `-O2`. Shall I force cmake to use `-O2` or we can try `-O3` in makefiles?

**Comment by stopiccot** [comment]
More questions about current Makefile:
- What is idea of passing `-O1` in `LDFLAGS_COMMON`? Does it actually change anyting?
- Is `-DPIC` in `CFLAGS_MODULE` actually needed?

**Comment by stopiccot** [comment]
`-DPIC` turns out to be completely useless so I removed it in a68e2dc8e35d411b9da27499cc69b06f1c960757

**Comment by stopiccot** [comment]
Passing `-O1` to linker also seems to be completely useless. Tested on Linux x86_64

**Comment by viciious** [comment]
Yes, -O2 should be used instead of -O3

**Comment by stopiccot** [comment]
I've pushed commit bde3a5d24322589dada6e62fddee002ac4498956 that makes cmake build settings the same to makefile settings. Still can't produce exactly the same binaries cause gcc stores source filenames in binaries and cmake passes absolute path instead of relative. Probably exactly the same binaries could be done via stripping. 

Anyway it would be nice to get any feedback about this iteration of cmake settings

**Comment by stopiccot** [comment]
I've compared current visual studio projects to generated ones. It seems that current project were upgraded many times so their settings are probably a bit outdated. Here is what i found:
- Current projects do not specify _General/Character Set_ option. Unicode is default value for new projects.
- _Linker/Advanced/Randomized Base Address_ is set to No. Yes is default value for new projects.
- _Linker/Advanced/Data Execution Prevention (DEP)_ is not set. Yes is default value for new projects.
- _Linker/General/Enable Incremental Linking_ is set to No. Yes is default value for new projects.
- In _C/C++/Preprocessor/Preprocessor Definitions_ there is a _VC80_UPGRADE=0x0710 definiton in inherited values. Don't know what it stands for.

All goes for Debug configuration.

**Comment by viciious** [comment]
Alles gut then

**Comment by stopiccot** [comment]
Em...? Shouldn't we switch to default values in these cases?

**Comment by viciious** [comment]
That's what I mean. We can leave the default values. Make sure Link Time Optimization is enabled though.

**Comment by stopiccot** [comment]
You misunderstood me. We do not use default values. They are disabled for current projects

**Comment by viciious** [comment]
If the cmake-generated projects do have those options as default, I'm fine with it.

**Comment by stopiccot** [comment]
Ok, what about testing them and proving some feedback?
You can generate them by running: `cmake -G "Visual Studio 12" .`

**Comment by viciious** [comment]
The generated solution includes some weird projects such as: ALL_BUILD and ZERO_CHECK.

Also, both game and ui should depend on angelwrap.

Whole program optimization is turned off.

**Comment by stopiccot** [comment]
ZERO_CHECK is a meta-target on which all other targets depend. It's needed to check if cmake files had changed and regenerate visual studio projects if needed. You can remove this taget by running
`cmake -G "Visual Studio 12" -DCMAKE_SUPPRESS_REGENERATION=1 .` but in this case you'll need manually regenerate projects each time you change cmake files.

**Comment by stopiccot** [comment]
Whole program optimization should be turned on in Release configuration

**Comment by stopiccot** [comment]
Target dependency fixed in 83c9afebeb11adb5d393aa772973a1204c416d07

**Comment by stopiccot** [comment]
Anything else you find uncomfortable with generated vs projects?

**Comment by viciious** [comment]
I believe we shouldn't default to unicode character set because that's causing compilation warnings in places where chars are confused with wchars: MessageBox, CreateWindowEx calls, etc

**Comment by viciious** [comment]
One more thing: can we get rid of the custom Makefile for libRocket and just use the stock cmake script?

**Comment by stopiccot** [comment]
I've removed unicode settings. Regarding removing makefile for libRocket it's on my list but I realised that makefiles are actually used for final builds compared to visual studio projects that are used for development only. So taking into account that removing makefiles is much bigger change I think finish we should be done with visual studio projects first.

**Comment by viciious** [comment]
I will test the generated projects later today.

**Comment by viciious** [comment]
> Whole program optimization should be turned on in Release configuration

It's not

**Comment by stopiccot** [comment]
Em... That's really weird. Thats what i have:

![image](https://cloud.githubusercontent.com/assets/24836/6155417/3da00ef0-b244-11e4-9eff-8d273306aa01.png)

**Comment by viciious** [comment]
It's on the General tab:
http://imgur.com/j62nirC

**Comment by stopiccot** [comment]
Seems like we found one more tiny cmake flaw. There is no option that will set Whole Program Optimization in General tab to any value other than "No Whole Program Optimization". But it's not a big deal cause it's kinda proxy-setting. Choosing it to "Use Link Time Code Generation" just sets C/C++/Optimization/Whole Program Optimization to /GL and Linker/Optimization/Link Time Code Generation to /LTCG. I fixed cmake scripts so they set both this flags in Release builds so things will actually work despite not being shown in General tab. I'll submit cmake bug later.

**Comment by stopiccot** [comment]
any updates on this?

**Comment by viciious** [comment]
Another thing that bothers me is that the main project lists _all_ libsrcs libraries as link dependencies, occasionally adding the same library multiple times:
 kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib;..\Release\libs\cin.lib;....\win32\x86\lib\release\curllib_static.lib;....\win32\x86\lib\release\zlib.lib;ws2_32.lib;winmm.lib;dxguid.lib;....\win32\x86\lib\release\libogg_static.lib;....\win32\x86\lib\release\libvorbisfile_static.lib;....\win32\x86\lib\release\libvorbis_static.lib;....\win32\x86\lib\release\libogg_static.lib;....\win32\x86\lib\release\libvorbisfile_static.lib;....\win32\x86\lib\release\libvorbis_static.lib;....\win32\x86\lib\release\libtheora_static.lib

The following libs need to go away:
..\Release\libs\cin.lib;....\win32\x86\lib\release\libogg_static.lib;....\win32\x86\lib\release\libvorbisfile_static.lib;....\win32\x86\lib\release\libvorbis_static.lib;....\win32\x86\lib\release\libogg_static.lib;....\win32\x86\lib\release\libvorbisfile_static.lib;....\win32\x86\lib\release\libvorbis_static.lib;....\win32\x86\lib\release\libtheora_static.lib

UI is linked against freetype

game is linked against ;....\win32\x86\lib\release\angelscript.lib

**Comment by viciious** [comment]
Btw, wouldn't it be better if ....\win32\x86\lib\release were added as an additional library path instead of this copy&paste-athon?

http://www.cmake.org/pipermail/cmake/2008-May/021730.html

**Comment by stopiccot** [comment]
> Library dependencies are transitive by default with this signature. When this target is linked into another target then the libraries linked to this target will appear on the link line for the other target too.

http://www.cmake.org/cmake/help/v3.0/command/target_link_libraries.html

It seems like it's a default cmake behavior. Probably for static libs. And it seems that it can't be disabled globally with a single line of code. Do you hate behavior this so much that we should introduce some hacks? :)

Regarding full library names. Your idea with library path would work if we used plain library names instead of obtaining them by `find_package()`. But believe me `find_package()` is much better way to link with libraries in cross-platform way so we probably should live with full names. And it's really not a big deal in the end. No one ever should look there anyway.

**Comment by stopiccot** [comment]
`set_target_properties(<TARGET_NAME> PROPERTIES LINK_INTERFACE_LIBRARIES "")`
for each target can solve this problem. But Do we really need that?

**Comment by viciious** [comment]
Ye I do hate it pretty much. I've been struggling to keep things clean and keep dependencies at minimum and here comes cmake with its retarded transitive linking.

**Comment by stopiccot** [comment]
Do chained libraries really affect output binaries? Cause if not I suggest to trade more clean cmake scripts for a bit messy generated projects not vice-versa. But if you insist I'll add LINK_INTERFACE_LIBRARIES fix. So final decision?

**Comment by viciious** [comment]
I prefer messy cmake scripts to increased linking time.

**Comment by stopiccot** [comment]
Ok, it seems that cin linking to client was the only case of transitive linking and its removed now. Anyway i've added PRIVATE keywork to all linking calls so this problem never occurs in future.

**Comment by viciious** [comment]
While you're at it, mind bumping C++ version requirement to C++11?

**Comment by viciious** [comment]
Never mind, fixed all of the remaining stuff myself.

**Comment by viciious** [comment]
@stopiccot Neither libRocket nor angelscript inherit CFLAGS/CXXFLAGS from the main project and thus can not compile anymore (mainly due to the missing -std=c++0x).
It is important that the same compilation and linking flags are applied to _all_ libraries.

**Comment by viciious** [comment]
@stopiccot btw, how can I generate cross-compilation Makefile for mingw x86 and x64?

**Comment by stopiccot** [comment]
On buildbot it's being configured like this:

```
cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/x86_64-mingw.cmake
cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/i686-mingw.cmake
```

**Comment by viciious** [comment]
@stopiccot Why is it i386-linux-gnu and not i686-linux-gnu btw?

2015-02-21 15:53 GMT+03:00 Alexey notifications@github.com:

> On buildbot it's being configured like this:
> 
> cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/x86_64-mingw.cmake
> cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/i686-mingw.cmake
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/142#issuecomment-75370381.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
Don't remember tbh, I think it's mainly because of `set(CMAKE_SYSTEM_PROCESSOR "i386")` and setting it to i686 can break things: binaries will use it as a suffix, multi-arch distroes use /usr/lib/i386-linux-gnu/ as a library path for non-64-bit libs.

**Comment by viciious** [comment]
How do I disable generation of static libraries (angelwrap.a, cgamea and so on) for mingw builds? We don't need them for the game..

**Comment by stopiccot** [comment]
Em, not sure I understand that. angelwrap and cgame are compiled as shared libraries. And I thought we actually need them.

**Comment by viciious** [comment]
Shared libraries - yes, but not the static ones. The .a files are not needed.

**Comment by viciious** [comment]
As of now, for whatever reasons, mingw compiles both shared and static libraries:
`Linking CXX shared library ../build/libs/angelwrap_x64.dll`
`Creating library file: ../build/libs/libangelwrap.dll.a`

`Linking CXX shared library ../build/basewsw/cgame_x64.dll`
`Creating library file: ../build/basewsw/libcgame.dll.a`

**Comment by stopiccot** [comment]
hm, maybe it's just trying to mimic visual studio behaviour when you always get .lib for each .dll. Btw how we deal with this on windows?

**Comment by viciious** [comment]
We don't.
In the case of mingw, it's just a minor packaging inconvenience as I had to add more packaging steps to remove the *.a files. Nothing major, I just thought it'd be handy to be able to somehow disable the generation of those files.

**Comment by viciious** [comment]
> adem
> btw seems like after all those build changes resulting binares became a lot bigger on win32_x64 at least, i.e. ui_x64.dll is about 8MB now, while it was 4-5MB before. other files got 40~50% to their size.

**Comment by viciious** [comment]
Mingw is missing all optimization flags (again!)

**Comment by viciious** [comment]
This whole cmake thing is so trashy it's not even funny.

As the result of the transition, we've lost all proper compilation settings for mingw, cross-compilation is such a pain now, I can't even compile x86 bins on linux anymore and native mingw builds simply do not exist.

We've lost more than we've gained.

**Comment by stopiccot** [comment]
Yeah, it's my bad I still haven't fixed mingw flags. Had some personal issues. I thought that for mingw we can still use handcrafted Makefile until cmake is fixed. Anyway, besides broken mingw. What is the problem with x86 linux-to-linux crosscompilation?

**Comment by viciious** [comment]
Well, I use the libs from libsrcs to cross-compile x86 bins since some of the libs shipped with Debian/Ubuntu are not multi-arch compatible, libcurl being one notable example.

**Comment by stopiccot** [comment]
Em... yeah there are still a lot of libs that a not multi-arch compatible, that's why we always had a hack in https://github.com/Warsow/qfusion-xcompile/blob/master/inc/gcc-setup.sh that just unpacks i386 deb's  and copies them to /usr. A proper way would be probably to have x86 vm for that. But that's a Ubuntu/Debian issue that always existed and I don't understand how this is connected to make-vs-cmake thing.

**Comment by viciious** [comment]
The old "Makefile" could be tuned to use the libs and headers from libsrcs/, not the system-wide ones. And in fact, this is how it's been working on our Debian system for a while.

**Comment by stopiccot** [comment]
So those force-installed-i386-debs never were actually used??

**Comment by viciious** [comment]
They were until we moved from Ubuntu to an older Debian stable.

**Comment by stopiccot** [comment]
Ok... But i don't see any options in Makefile for using libsrcs libs in non-mingw mode? It's done solely by exporting env vars?

**Comment by viciious** [comment]
Yes, it's all about passing proper CFLAGS and LDFLAGS to make invocation.

**Comment by viciious** [comment]
Well, I don't really care about lin/x86 that much: it's fixable but gonna take some patience from me. The lack of optimization settings in mingw builds is more disturbing.

**Comment by stopiccot** [comment]
Ok, I've pushed some mingw fixes. Can you please check them?

**Comment by viciious** [comment]
Will do. But first I need to fix lin/x86. So far I've been unable to successfully link the cin library:

> Linking C shared library ../build/libs/cin_i386.so
> /usr/lib/i386-linux-gnu/libogg.so: could not read symbols: File in wrong format
> collect2: error: ld returned 1 exit status

Linking cmd:

> /usr/bin/cc  -fPIC  -pipe -Wall -Wno-unused-function -fvisibility=hidden -Winvalid-pch -O3 -DNDEBUG -fno-strict-aliasing -ffast-math -funroll-loops -msse2 -O2  -Wl,--as-needed  -s -shared  -o ../build/libs/cin_i386.so CMakeFiles/cin.dir/cin_theora.c.o CMakeFiles/cin.dir/cin_syscalls.c.o MakeFiles/cin.dir/cin_roq.c.o CMakeFiles/cin.dir/cin_main.c.o CMakeFiles/cin.dir/cin.c.o CMakeFiles/cin.dir/**/gameshared/q_shared.c.o CMakeFiles/cin.dir/**/gameshared/q_math.c.o /usr/lib/i386-linux-gnu/libogg.so /usr/lib/i386-linux-gnu/libvorbisfile.so /usr/lib/i386-linux-gnu/libvorbis.so /usr/lib/i386-linux-gnu/libogg.so /usr/lib/i386-linux-gnu/libtheoradec.so /usr/lib/i386-linux-gnu/libvorbisfile.so /usr/lib/i386-linux-gnu/libvorbis.so /usr/lib/i386-linux-gnu/libtheoradec.so

The .so file in question is definitely for 32-bit arch. Any ideas?

**Comment by stopiccot** [comment]
hm, looks weird... ok i'll try to reproduce this one for me. You are using Debian 7 right?

**Comment by viciious** [comment]
Yes. Turns out I was missing -m32 in cmake c flags but now it's a different error.. Sigh.

**Comment by stopiccot** [comment]
Oh... my bad. I really missed that. Actually buildbot uses

```
cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/i386-linux-gnu.cmake -DCMAKE_FIND_ROOT_PATH=~/deb/temp -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
```

to build x86 Linux build. Dunno why I haven't moved those settings to toolchain file. And it seems that I've  set search path instead of copying i386-debs to /usr. Which is probably a better idea cause even header files can differ in x86_64 and i386 packages and you don't want them to be overwritten.

**Comment by stopiccot** [comment]
And there was a [comment](https://github.com/Warsow/qfusion/blob/master/source/cmake/i386-linux-gnu.cmake#L1) in a toolchain file all this time...

**Comment by stopiccot** [comment]
Sorry, I really forgot about that. And mingw crosscompilation doesn't require any additional flags as you can see.

**Comment by stopiccot** [comment]
Anyway I suggest to fix qfusion-xcompile init scripts not to overwrite /usr files but use this kinda-chroot way for non-multiarch-ready packages.

**Comment by stopiccot** [comment]
And probably we can edit main CMakeLists file with a condition to add -m32 flag for i386 builds so we don't need to pass them in command line, but that is up to you I'm actually fine with both.

**Comment by viciious** [comment]
Well, I hacked my way through with this commit:
https://github.com/Warsow/qfusion/commit/1ce8cd078c8775f3cf6f4d6b4a42697b14f2af63

**Comment by viciious** [comment]
As a workaround for probs with libcurl, I've dropped headers, .so and .a files produced by compile_lib.sh stage into CMAKE_FIND_ROOT_PATH.

Now, we only need to fix the size of binaries produced by mingw.

**Comment by stopiccot** [comment]
What errors you are getting compiling with system-one curl?

**Comment by viciious** [comment]
Linking C executable ../build/wsw_server.i386
/usr/bin/ld: warning: libssh2.so.1, needed by /home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: liblber-2.4.so.2, needed by /home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libldap_r-2.4.so.2, needed by /home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgssapi_krb5.so.2, needed by /home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: librtmp.so.0, needed by /home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so, not found (try using -rpath or -rpath-link)
/home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so: undefined reference to `gss_release_name@gssapi_krb5_2_MIT'
/home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so: undefined reference to`libssh2_userauth_list'
/home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so: undefined reference to `GSS_C_NT_HOSTBASED_SERVICE@gssapi_krb5_2_MIT'
/home/buildbot/deb/temp/lib/i386-linux-gnu/libcurl.so: undefined reference to`libssh2_sftp_stat_ex'
...

**Comment by stopiccot** [comment]
That's because x86_64 package was installed by `apt-get install` which installs also all dependencies. By manually downloading deb and unpacking it you lose dependencies.

**Comment by viciious** [comment]
This is i386...

**Comment by stopiccot** [comment]
I ment that x86_64 package was installed by `apt-get install` that's why all x86_64 dependencies are also installed. i386 package was installed by manually downloading that's why all i386 dependencies are missing.

**Comment by viciious** [comment]
I did install all its dependencies manually. Well, anyway, we don't want warsow to depend on stuff such as kerberos or NTLM or whatever. I'll probably override the system-wide dependencies for x86_64 libcurl as well.

**Comment by stopiccot** [comment]
You probably still missed some. Or maybe package was updated and introduced new dependencies.

**Comment by viciious** [comment]
Most likely, /home/buildbot/deb/temp/lib/i386-linux-gnu/ was missing from rpath indeed. The proper .so files were there but ignored.

**Comment by viciious** [comment]
Done.

**Comment by stopiccot** [comment]
So... i'm back. Can you update me on this one? Is everything OK with linux and mingw builds? What about build size? Can we remove manually-crafted Makefile?

**Comment by viciious** [comment]
It sorta works now. The prob was that our cmake script doesn't default to any kind of build: it's neither debug nor release.. Adding -DCMAKE_BUILD_TYPE=Release to our buildbot scripts fixed compilation flags.

**Comment by stopiccot** [comment]
So https://github.com/Warsow/qfusion/blob/master/source/CMakeLists.txt#L93 is not working?

**Comment by viciious** [comment]
I suppose it doesn't.
