### ISSUE TITLE
[Linux/X11/XI2] Keyboard doesn't work after running the game from Steam

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#144]
As topic says Steam doesn't allow keyboard input to work with the latest dev QF/WSW version. After a little research I've found that such behivour was caused by my X11 input patch which enabled Alt+Tab/background keys support by not grabbing keyboard at all https://github.com/Warsow/qfusion/commit/1e2d16305276c6c9bfe4efcbd7019fe674ec8e0f But reverting that patch would result that Alt+Tab/Steam Overlay/any other background shortkeys wont work. I really dunno what exactly causes such behevoir, but may be Steam grubs keyboard completely and doesn't give it back to the game, or it is because of Steam shipping with its own versions of some libraries (the "Steam Runtime") in an attempt to emulate the Ubuntu 12.04 environment.

Tried SDL2 version, and it seems to work nicely w/o any conflicts except other not yet fixed SDL2's things.

So here are possible solutions from my view:
1) Revert that X11 patch only for Steam version of the game (by #ifdef **STEAM** or smth).
2) Using SDL2 for input at least for Steam version (but still there is now raw mouse input).
3) Wait for someone to fix it in our X11 input implementation.
4) Or if it is Steam issue, wait till they fix it, but it is gonna take too much time (i'm gonna post similar issue in their repo later).

**Comment by viciious** [comment]
Posting this for reference:
https://wiki.libsdl.org/SDL_HINT_GRAB_KEYBOARD

**Comment by viciious** [comment]
A random shot in the dark:
does calling XRaiseWindow(x11display.dpy, x11display.win); in install_grabs_keyboard help by any chance?

**Comment by adem4ik** [comment]
calling XRaiseWindow(x11display.dpy, x11display.win); in install_grabs_keyboard didn't help.

accidentally it was found that changing "mask.deviceid = XIAllMasterDevices;" to "mask.deviceid = XIAllDevices;" in https://github.com/Warsow/qfusion/blob/1e2d16305276c6c9bfe4efcbd7019fe674ec8e0f/source/unix/unix_input.c#L338 makes the trick but only for running the game from Steam. 

w/o Steam there are new problems appear after applying this change:
- default console button "~" stops to work;
- chat gets each pressed key twicely;
- also ESC not always works.

I have to admit that i really don't understand the difference between XIAllMasterDevices & XIAllDevices, so I'm still googling...

**Comment by viciious** [comment]
It appears that SDL2 doesn't use XInput2 for kb input at all..

Anyway, I don't mind switching to SDL2 for everything Linux as long as there's no functionality loss.

**Comment by adem4ik** [comment]
I'm still thininkg of Xinput2 implementation, so here is my guess to the previous message:
XIAllDevices = Master + Slave devices
XIAllMasterDevices = Only Master devices

So "mask.deviceid = XIAllDevices;" provides 2x keyboard events (master & slave) for running the game w/o Steam (console gets opened and closed immediately), and only 1x keyboard events (slave) for running with Steam.

**Comment by viciious** [comment]
So, we could listen to events from all devices and then filter those coming from master devices

**Comment by viciious** [comment]
Did switching to SDL help?

**Comment by adem4ik** [comment]
Yes, it did! buttons work fine in-game, Steam Overlay can be opened, any background shortcut works as it should be.
