### ISSUE TITLE
libRocket submodule

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#149]
Considering we maintain our own fork of libRocket at github and constant merges from that fork to qfusion maybe we should make it submodule?

**Comment by viciious** [comment]
It already is: I'm using git subtrees to merge changes from the upstream
module.

2015-02-18 14:56 GMT+03:00 Alexey notifications@github.com:

> Considering we maintain our own fork of libRocket at github and constant
> merges from that fork to qfusion maybe we should make it submodule?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/149.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
But this seems to be working only on your local machine. I've pushed OS X fixes to Warsow/libRocket and now wonder how I should correctly merge them cause for me libRocket folder in Warsow/qfusion is just a folder.

**Comment by viciious** [comment]
git subtree pull --prefix libsrcs/libRocket/libRocket
https://github.com/Warsow/libRocket.git master --squash

2015-02-18 16:31 GMT+03:00 Alexey notifications@github.com:

> But this seems to be working only on your local machine. I've pushed OS X
> fixes to Warsow/libRocket and now wonder how I should correctly merge them
> cause for me libRocket folder in Warsow/qfusion is just a folder.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/149#issuecomment-74863647.

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
```
git subtree pull --prefix libsrcs/libRocket/libRocket https://github.com/Warsow/libRocket.git master --squash 
```

ty
