### ISSUE TITLE
Transparency effect of picked items & cg_simpleitems 1|2

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#15]
So the transparency effect is a feature =) but it works well only with 3D items (cg_simpleitems 0). With 2D items (cg_simpleitems 1|2) it doesn't. After picking item its icon is drawn with zero transparency & it looks like item is still available for pick.

**Comment by viciious** [comment]
Thanks, I'll look into this.

2013/9/5 Andrei Stepanov notifications@github.com

> So the transparency effect is a feature =) but it works well only with 3D
> items (cg_simpleitems 0). With 2D items (cg_simpleitems 1|2) it doesn't.
> After picking item its icon is drawn with zero transparency & it looks like
> item is still available for pick.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/15
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Fixed in qfusion and warsow repositories.

**Comment by adem4ik** [comment]
Somehow this fix doesn't work for me, there is still no transparency on picked 2D items.

**Comment by viciious** [comment]
As I said, the fix has its counterpart in warsow repository. Simpleitem
shaders need to be changed to use 'alphagen entity', to be more precise.

2013/9/6 Andrei Stepanov notifications@github.com

> Somehow this fix doesn't work for me, there is still no transparency on
> picked 2D items.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/15#issuecomment-23927230
> .

## 

Best regards,
 Victor Luchitz
