### ISSUE TITLE
"Error: Download message while not dowloading"

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#150]
Steps to reproduce:
1) cg_autoaction_demo "1"
2) join the server with available server-side demos and low upload speed
3) start to down any demo with "demoget <XX>"
4) press F4 (ready)
5) demo downloading must complete only after the match start!
6) after the match end, open the demo which was recorded by cg_autoaction_demo

Result: console full of "Error: Download message while not dowloading"
Example demo: https://yadi.sk/d/l8wxqlKAexEjx

Demo was recorded on 1.5. I didn't manage to test it on 1.6, as our test server has too high upload speed, so I couldn't reach the conditions :D

**Comment by viciious** [comment]
svc_download packets should be silently ignored during demo playback. Although I find it bizarre that such packets are recorded in the first place as that it makes it possible to embed a demo into another demo.

**Comment by viciious** [comment]
Fixed in a19690de08b25e8c8ea146f46c5dd62d0760311f
