### ISSUE TITLE
Angelscript 2.30

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#154]
Should we upgrade?

**Comment by Triang3l** [comment]
I don't know, but if we upgrade, I think we should remove the prebuilt library from win32/bin. It's easy to setup and build, it doesn't need things like configs.

**Comment by stopiccot** [comment]
Dunno, adding it to qfusion compilation will make build longer. Making it a one-time build setup makes no sense also just making setup one bit more complicated.

**Comment by viciious** [comment]
Angelscript 2.30 appears to have had too many code changes to be stable.

**Comment by viciious** [comment]
On top of that, our array and dictionary addons are heavily customized. Porting them over again is going to be painful.

**Comment by viciious** [comment]
We're going to stick to AngelScript 2.29.2

**Comment by stopiccot** [comment]
Ah, whatever, I've just committed cmake files from 2.30. That's all I needed
