### ISSUE TITLE
Pass bool stereo to R_Init

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#171]
Querying cl_stereo cvar from glw is just wrong.

**Comment by Triang3l** [comment]
Can it be removed entirely in favor of a true barrel distortion mesh?

**Comment by viciious** [comment]
No idea. I don't even know whether it's still working.

**Comment by viciious** [comment]
9c574145ce2ec49d0e7e4041ace71d4eb8e53c6b
