### ISSUE TITLE
Broken plasma climb on the rotated walls

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#176]
Description: every wall which is rotated and not parallel to X & Y axis can't be used for plasma climb properly. You can only reach about 2x of the player model height, and after that you just stop to get vertical acceleration.

Here is a video on wdm6, wdm2, wdm5 and cocaine_b2: http://www.youtube.com/watch?v=LjPSjdZP_x4

Last map has a lot of such wall and most of them are broken for that trick, can be downloaded here: http://chiefin.net/chiefin/files/warsow/basewsw/cocaine_b2.pk3

**Comment by adem4ik** [comment]
Ah forgot to say, this bug exists in wsw1.0 & wsw1.5 too.

**Comment by viciious** [comment]
What about earlier versions?

2015-05-20 19:18 GMT+03:00 Andrei Stepanov notifications@github.com:

> Ah forgot to say, this bug exists in wsw1.0 & wsw1.5 too.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Warsow/qfusion/issues/176#issuecomment-103945327.

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
My wild guess is that this's got something to do with
https://github.com/Warsow/qfusion/blob/master/source/game/g_combat.cpp#L72

2015-05-20 21:55 GMT+03:00 Victor Luchitz vluchits@gmail.com:

> What about earlier versions?
> 
> 2015-05-20 19:18 GMT+03:00 Andrei Stepanov notifications@github.com:
> 
> > Ah forgot to say, this bug exists in wsw1.0 & wsw1.5 too.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Warsow/qfusion/issues/176#issuecomment-103945327.
> 
> ## 
> 
> Best regards,
>  Victor Luchitz

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Ah well, this is a nasty side-effect of G_SplashFrac... The distance from AABB's centerpoint to the impact point is shorter in case of non-aligned walls hence smaller knockback.

**Comment by adem4ik** [comment]
as a note: bug is presented since wsw0.5, wsw0.4 had different splash formula

**Comment by viciious** [comment]
it's not about about the formula.. 0.4 still had the same bug despite of the different formula for knockback

**Comment by viciious** [comment]
Closing as WONTFIX. Linking relevant QuakeLive thread: http://www.quakelive.com/forum/showthread.php?26936-Cylinder-hit-detection-instead-of-box-hit-detection&p=229578&viewfull=1#post229578
