### ISSUE TITLE
Walljump shifting

### ISSUE THREAD

**Issue by hettoo** [Qfusion/qfusion#18]
The walljump code traces from the player origin some distance into several directions to look for walls.
For no apparant reason, these end position vectors are scaled up a little bit: https://github.com/viciious/qfusion/blob/3c66d65b4f91576ac7932715f3b9c2826fe73224/source/gameshared/gs_pmove.c#L170
At large distances, this causes walls facing towards the world origin to be walljumpable from a larger distance, while disabling walljumps on walls on the other side.

**Comment by viciious** [comment]
And your suggestion is to...?

2013/9/6 Gerco van Heerdt notifications@github.com

> The walljump code traces from the player origin some distance into several
> directions to look for walls.
> For no apparant reason, these end position vectors are scaled up a little
> bit:
> https://github.com/viciious/qfusion/blob/3c66d65b4f91576ac7932715f3b9c2826fe73224/source/gameshared/gs_pmove.c#L170
> At large distances, this causes walls facing towards the world origin to
> be walljumpable from a larger distance, while disabling walljumps on walls
> on the other side.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/18
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
Remove that line.
If it had a purpose the intention might have been to multiply the distance between the point and the player origin instead, but I can't think of any reason for this.

**Comment by viciious** [comment]
This kind of changes needs to be tested thoroughly as I'm somewhat afraid
it migh affect the movement in expected ways.

2013/9/6 Gerco van Heerdt notifications@github.com

> Remove that line.
> If it had a purpose the intention might have been to multiply the distance
> between the point and the player origin instead, but I can't think of any
> reason for this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/18#issuecomment-23935866
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
Honestly, it can't get much worse if you realize what it is doing at the moment.
This function is only called once, to determine if there is a wall within reach of the player against which he can walljump. Without this multiplication it does that just fine.
This has been bugging racers for a long time (the shifting overpowers the walljump margin after 8000 units, which is nothing in race).

If you have some time, play around with this map: https://dl.dropboxusercontent.com/u/22044693/wallbug.pk3
Go to one of the red cubes and notice the difference in maximum distance still allowing walljumps on the  sides of it.

Anyway, it would be great if this could be tested for an eventual next release.

**Comment by viciious** [comment]
Does the change fix the wj bug observed on those red cubes?

2013/9/6 Gerco van Heerdt notifications@github.com

> Honestly, it can't get much worse if you realize what it is doing at the
> moment.
> This function is only called once, to determine if there is a wall within
> reach of the player against which he can walljump. Without this
> multiplication it does that just fine.
> This has been bugging racers for a long time (the shifting overpowers the
> walljump margin after 8000 units, which is nothing in race).
> 
> If you have some time, play around with this map:
> https://dl.dropboxusercontent.com/u/22044693/wallbug.pk3
> Go to one of the red cubes and notice the difference in maximum distance
> still allowing walljumps on the sides of it.
> 
> Anyway, it would be great if this could be tested for an eventual next
> release.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/18#issuecomment-23944677
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
Yeah.

**Comment by viciious** [comment]
The original intention was probably this:
        dir[0] = pml.origin[0] + (pm->maxs[0]_cos((360/nbTestDir)_i)) *
1.002; // cos( (360/Imax) \* i )
        dir[1] = pml.origin[1] + (pm->maxs[1]_sin((360/nbTestDir)_i)) *
1.002;

2013/9/6 Gerco van Heerdt notifications@github.com

> Yeah.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/18#issuecomment-23945861
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Fixed.

**Comment by hettoo** [comment]
That would be my guess as well.

Thanks! :)
