### ISSUE TITLE
Grenades getting stuck in the walls

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#181]
How it looks like: https://youtu.be/wOh-ef36x1E
As you can see, i don't move my mouse, but this stuck doesn't happen constantly, but quite often. As you can notice there is only one sound of grenade bounce is played. Also stuck doesn't happen if i use zooming with zoomfov <= 50. 

My guess it may happen because of friction effect which Warsow's grenades have. Just take a look on this video where i compare wsw and q3 grenades fired closely to the floor horizontal: http://youtu.be/ABjyB67CPWM

As you can see q3 grenades always bounce for 3 times no matter what, while wsw grenades may not bounce at all depending on the angle. The last case looks similar the bug described here, since you can hear only one sound of grenade touching the floor.

p.s. here is a demo of that stuck: https://yadi.sk/d/DNb-D2r4h2Dem

**Comment by adem4ik** [comment]
Can't reproduce it anymore.

More likely it was fixed by this commit https://github.com/Qfusion/qfusion/commit/f5b27f8077dae635ae12671e5f16b7d5a09ade69

**Comment by viciious** [comment]
Yay
