### ISSUE TITLE
[AI] [Suggestion] Apply botnotarget on a player which is chatting, alt-tabbing, using menu, etc

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#184]
There is one thing that I really liked in Q3 CPMA: bots don't attack you when you're typing a message or using console. I think it would be a really useful feature for our bots too, especially for newcomers since they like to visit chat, menu, console while setting up stuff or asking for something. It is always feels unfair when somebody kills you while you're in afk mode, we can't insist players to stop it, but applying botnotarget won't hurt at all.

**Comment by viciious** [comment]
a97c0cc4312f8827be91671117febce351843edb This should be enough.
