### ISSUE TITLE
Black screen after upgrading to FXAA 3.11

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#19]
r_fxaa 0
![wsw_130907_142909](https://f.cloud.github.com/assets/4707112/1101115/b95bb8a6-17a8-11e3-9e4c-92ec5d4bed67.jpg)
r_fxaa 1
![wsw_130907_142921](https://f.cloud.github.com/assets/4707112/1101116/be2c84c8-17a8-11e3-8562-4b899ede1747.jpg)

Before upgrading r_fxaa was working fine
![wsw_130907_143405](https://f.cloud.github.com/assets/4707112/1101120/17c20102-17a9-11e3-90c6-2dabc4ce74b7.jpg)

**Comment by adem4ik** [comment]
console log attached: http://pastebin.com/wMwYf1j3

I guess the problem is:
"Failed to compile fragment shader for program defaultFXAA:
0(1350) : error C7532: global function textureGather requires "#version 400" or later
0(1350) : error C0000: ... or #extension GL_ARB_gpu_shader5 : enable
0(1351) : error C7532: global function textureGatherOffset requires "#version 400" or later
0(1351) : error C0000: ... or #extension GL_ARB_gpu_shader5 : enable"

**Comment by viciious** [comment]
Should be fixed now.

**Comment by adem4ik** [comment]
ye, everything seems fine now.

**Comment by adem4ik** [comment]
Well https://github.com/viciious/qfusion/issues/13 was fixed, but looks like that issue appear now: I get Black Screen after turning on r_fxaa 1 (2,4).

Here is console output: http://yadi.sk/d/38qPH4bs9oQr3

**Comment by viciious** [comment]
Fixed

2013/9/24 Andrei Stepanov notifications@github.com

> Well #13 https://github.com/viciious/qfusion/issues/13 was fixed, but
> looks like that issue appear now: I get Black Screen after turning on
> r_fxaa 1 (2,4).
> 
> Here is console output: http://yadi.sk/d/38qPH4bs9oQr3
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/19#issuecomment-24992151
> .

## 

Best regards,
 Victor Luchitz
