### ISSUE TITLE
[Linux] Game releases all the unheard sounds after alt-tabbing back to it

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#198]
It seems like if you alt+tab out of the game, engine accumulates all the unheard sounds in its memory, and then releases them at once when you make alt+tab back to its window. Happens only on Linux with both sound modules - qfusion's one and openal.

https://youtu.be/giMcE1z8pq8

**Comment by viciious** [comment]
Sounds like PulseAudio issue tbh (pun unintended).

**Comment by adem4ik** [comment]
Seems like you're right, just checked the same action with ALSA only, and there was no such issue. Even though I can't reproduce it in other games that can alt+tab like Dota 2.

**Comment by viciious** [comment]
Try commenting out everything inside S_Activate here:
https://github.com/Warsow/qfusion/blob/master/source/sdl/sdl_snd.c

**Comment by adem4ik** [comment]
Tried Xonotic executed by xonotic-linux64-sdl, it doesn't have that issue.

commenting out everything inside S_Activate makes sound being played everytime no matter what, as our s_globalfocus 1 does.

**Comment by viciious** [comment]
I think this was resolved in 42ad2c96e6835a4e73f57b0a7a4dc65575d04ae7
