### ISSUE TITLE
Minor enhancement on item's ghost alpha

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#20]
Here is the comparison of items before and after picking. Red number is the value of alpha. (cg_ents.cpp (904) cent->ent.shaderRGBA[3] = 127;)
![items](https://f.cloud.github.com/assets/4707112/1102823/37c71d8e-1862-11e3-9389-a6c62597b5fb.png)

Left side is showing current behavior, where you can see that there is not so much differency between available & not available health bubbles. Right side is showing how it can be after changing value from 127 to 63.

**Comment by adem4ik** [comment]
or i would rather suggest an option like cg_itemsGhostAlpha with range from 127 to 0 to prevent ppl's whining about it.

**Comment by hettoo** [comment]
When doing some test plays with the engine I got confused many times because of this small difference between the two states for some items, so I would really recommend a small (default) value as well, perhaps even around 40.

On a side note, what about removing the scaling respawn effect? Replacing the placeholder with an upscaling new item seems messy to me, especially considering the fast-paced and minimalist nature of the game. Just an opinion though.
Quick example: https://github.com/hettoo/qfusion/tree/items

**Comment by viciious** [comment]
Well, I took a somewhat different approach to make the ghost items appear
more "ghostly": checkout the HEAD revision @ master

2013/9/8 Gerco van Heerdt notifications@github.com

> When doing some test plays with the engine I got confused many times
> because of this small difference between the two states for some items, so
> I would really recommend a small (default) value as well, perhaps even
> around 40.
> 
> On a side note, what about removing the scaling respawn effect? Replacing
> the placeholder with an upscaling new item seems messy to me, especially
> considering the fast-paced and minimalist nature of the game. Just an
> opinion though.
> Quick example: https://github.com/hettoo/qfusion/tree/items
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/20#issuecomment-24021135
> .

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
Looks a lot better and useful! thank you)

**Comment by viciious** [comment]
hettoo, what do you think? I've decided to keep the scaling effect because it's somewhat more pronounced than the alternatives.

**Comment by hettoo** [comment]
It's very nice. Fortunately the only item that might still cause a little confusion is the least popular one (machinegun being grey).
I do still find the scaling weird combined with this new feature, but I'll agree that there is no comparable alternative.
