### ISSUE TITLE
Fix buildbot

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#201]
http://ex60.stopiccot.com:8010/builders/Linux%20x86/builds/1388

:(

**Comment by stopiccot** [comment]
I've recreated linux virtual machine and forced builds. All-green for now. Will give a closer look if it reappears again.

**Comment by viciious** [comment]
Thanks!

**Comment by viciious** [comment]
http://ex60.stopiccot.com:8010/builders/MinGW%20x64/builds/1354/steps/shell_1/logs/stdio

**Comment by stopiccot** [comment]
I've googled that this issue can be caused by low memory. I've allocated 4Gb for linux vm seems to be fine for now.
