### ISSUE TITLE
No "gloss effect" on Grenade Launcher

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#21]
After running around the map and changing weapons I've found that there is no "gloss" on GL. It feels like every weapon is made from the plastic or metal except GL, which looks like made from the paper, as it only changes color but has no gloss.
Here is a comparison:
![weapons](https://f.cloud.github.com/assets/4707112/1122657/f51316ce-1ae0-11e3-9ed2-aa662695c610.png)
Also I've made a video, which should explain you more than I can. Just look at the weapon and nowhere else during my run.
http://yadi.sk/d/bcQVXMYK96S8N

P.S. I've noticed that "gloss effect" was changed a bit from wsw1.0x, more natural and cool now, or mb it is because weapons look a bit darker now... afaik there is a cvar named "gl_ext_texture_cube_map" which manages it.

**Comment by viciious** [comment]
Ok, I'll look into this. On a side note, the "gl_ext_texture_cube_map" cvar
is now obsolete.

2013/9/11 Andrei Stepanov notifications@github.com

> After running around the map and changing weapons I've found that there is
> no "gloss" on GL. It feels like every weapon is made from the plastic or
> metal except GL, which looks like made from the paper, as it only changes
> color but has no gloss.
> Here is a comparison:
> [image: weapons]https://f.cloud.github.com/assets/4707112/1122657/f51316ce-1ae0-11e3-9ed2-aa662695c610.png
> Also I've made a video, which should explain you more than I can. Just
> look at the weapon and nowhere else during my run.
> http://yadi.sk/d/bcQVXMYK96S8N
> 
> P.S. I've noticed that "gloss effect" was changed a bit from wsw1.0x, more
> natural and cool now, or mb it is because weapons look a bit darker now...
> afaik there is a cvar named "gl_ext_texture_cube_map" which manages it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/21
> .

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
sorry Vic, guess i've found the reason) it is not engine fault, looks like GL just has no "gloss.tga"
![glos](https://f.cloud.github.com/assets/4707112/1123147/254f164a-1aea-11e3-8546-421ce48fbd1b.png)

**Comment by adem4ik** [comment]
also there is no "gloss.tga" for instagun >.<

**Comment by viciious** [comment]
Well, I guess those guns aren't supposed to have any gloss on them then?

2013/9/11 Andrei Stepanov notifications@github.com

> also there is no "gloss.tga" for instagun >.<
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/21#issuecomment-24241897
> .

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
seems so :/
