### ISSUE TITLE
Add UI localization support

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#22]
libRocket provides [localization support](http://librocket.com/wiki/documentation/Localisation) via application's system interface. The engine/UI has to be able to:
- determine user's language settings
- load .PO files
- provide localized string, matching the supplied string identifier against msgid's loaded from .PO

**Comment by viciious** [comment]
Merged in commit b61777dd75

**Comment by adem4ik** [comment]
can't compile QF, console gives:

> Compiling client/l10n.c
> client/l10n.c: В функции «L10n_ParsePOString»:
> client/l10n.c:92:3: предупреждение: suggest parentheses around «&&» within «||» [-Wparentheses]
> client/l10n.c: В функции «L10n_CheckUserLanguage»:
> client/l10n.c:449:12: ошибка: «APP_DEFAULT_LANGUAGE» undeclared (first use in this function)
> client/l10n.c:449:12: замечание: each undeclared identifier is reported only once for each function it appears in
> make: **\* [buildx86_64/client/l10n.o] Ошибка 1

**Comment by viciious** [comment]
https://github.com/viciious/qfusion/blob/master/source/qcommon/version.h#L131

2013/10/5 Andrei Stepanov notifications@github.com

> can't compile QF, console gives:
> 
> Compiling client/l10n.c
> client/l10n.c: В функции «L10n_ParsePOString»:
> client/l10n.c:92:3: предупреждение: suggest parentheses around «&&» within
> «||» [-Wparentheses]
> client/l10n.c: В функции «L10n_CheckUserLanguage»:
> client/l10n.c:449:12: ошибка: «APP_DEFAULT_LANGUAGE» undeclared (first use
> in this function)
> client/l10n.c:449:12: замечание: each undeclared identifier is reported
> only once for each function it appears in
> make: **\* [buildx86_64/client/l10n.o] Ошибка 1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/22#issuecomment-25750658
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
May want to move that out of the conditional.

**Comment by viciious** [comment]
Fixed in e187faff9485abee2b74ce7f9e148e2f54408ee9

2013/10/5 Gerco van Heerdt notifications@github.com

> May want to move that out of the conditional.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/22#issuecomment-25750930
> .

## 

Best regards,
 Victor Luchitz
