### ISSUE TITLE
Small fix on EB's Wall impact puffs

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#23]
source/cgame/cg_effects.cpp (749 string):
by changing
CG_InitParticle( p, scale, a, r, g, b, shader );
to a copy of string 795
CG_InitParticle( p, 1.2f, 1, 0.8f + crandom()_0.1, 0.8f + crandom()_0.1, 0.8f + random()*0.1, NULL );

The idea of this fix is simple - to make wall impacts look in the same way as EB particle trail.
![wall](https://f.cloud.github.com/assets/4707112/1143585/05bf6888-1d48-11e3-8f60-99ede577ec8a.png)

**Comment by viciious** [comment]
Imo the impact isn't supposed to be of the same color as the trail, rather of the same color as the impact decal

**Comment by adem4ik** [comment]
sorry, didn't know that. i've just noticed that the only thing that changed after appealing this patch was EB impact. But I think that impacts should have same shape as other particles at least. Take a look at the left part of screenshot: particles has square shape, when explosion's, EB trail's particles are more like circle.

**Comment by viciious** [comment]
I think you're nitpicking :)

2013/9/14 Andrei Stepanov notifications@github.com

> sorry, didn't know that. i've just noticed that the only thing that
> changed after appealing this patch was EB impact. But I think that impacts
> should have same shape as other particles at least. Take a look at the left
> part of screenshot: particles has square shape, when explosion's, EB
> trail's particles are more like circle.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/23#issuecomment-24454143
> .

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
yes, as usual :D
