### ISSUE TITLE
Error: Failed to load default refresh DLL

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#24]
Latest Qfusion, Warsow doesn't want to start, console says:

Loading refresh module ref_gl... LoadLibrary (/home/adem/games/warsow_test/libs/ref_gl_x86_64.so):(/home/adem/games/warsow_test/libs/ref_gl_x86_64.so: undefined symbol: vid_displayfrequency)
Not found.
Error: Failed to load default refresh DLL

**Comment by viciious** [comment]
Should be fixed now.

**Comment by hettoo** [comment]
Same thing for vid_multiscreen_head now (should be the last one).

**Comment by viciious** [comment]
Fixed

2013/9/23 Gerco van Heerdt notifications@github.com

> Same thing for vid_multiscreen_head now (should be the last one).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/24#issuecomment-24915359
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Fixed, thanks.

Sorry about this, unix code was glue taped quite a long time and refactoring it now causes too much pain.

**Comment by adem4ik** [comment]
unfortunately it goes further, QFusion gets crashed during Xrandr extension initialisation:

X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Resource id in failed request:  0x0
  Serial number of failed request:  106
  Current serial number in output stream:  107

**Comment by viciious** [comment]
Please file a separate issue for this. Stacktrace would help too.

2013/9/23 Andrei Stepanov notifications@github.com

> unfortunately it goes further, QFusion gets crashed during Xrandr
> extension initialisation:
> 
> X Error of failed request: BadDrawable (invalid Pixmap or Window parameter)
> Major opcode of failed request: 53 (X_CreatePixmap)
> Resource id in failed request: 0x0
> Serial number of failed request: 106
> Current serial number in output stream: 107
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/24#issuecomment-24921696
> .

## 

Best regards,
 Victor Luchitz
