### ISSUE TITLE
X Error of failed request: BadDrawable

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#25]
Qfusion/Warsow gest crashed right after Xrandr initialisation (at least I guess so)
Console output: http://yadi.sk/d/LWFK67Aa9kk9D

I can make stacktrace only if you explain me how.

**Comment by hettoo** [comment]
With a debug build the assertion in HandleEvents (unix_input.c) fails because x11display.win evaluates to false.

(adem: http://www.warsow.net/forum/thread/t/215473#post-215473)

**Comment by hettoo** [comment]
Possible fix: https://github.com/hettoo/qfusion/commit/c2b3dde5e5da6c9937ee32edb467d500c097d7cc
Note that I had to remove the x11display->dpy = NULL from VID_Sys_Init because VID_WndProc isn't called yet.
Also note that I had to remove the #version stuff from r_program.c to prevent other crashes. Somehow that code had been causing my window to be black since https://github.com/viciious/qfusion/commit/902fe10ff1b448f0f0af285f6fecacbfb4e7de87.

Edit: added a workaround for that dpy reset. Assuming it was meant to initialize it, it is only reset the first time. #version crash turned out to be caused by a superfluous Com_Printf token.

**Comment by viciious** [comment]
Pushed a somewhat less intrusive possible fix, please check it out.

2013/9/23 Gerco van Heerdt notifications@github.com

> Possible fix: hettoo@c2b3ddehttps://github.com/hettoo/qfusion/commit/c2b3dde5e5da6c9937ee32edb467d500c097d7cc
> Note that I had to remove the x11display->dpy = NULL from VID_Sys_Init
> because VID_WndProc isn't called yet.
> Also note that I had to remove the #version stuff from r_program.c to
> prevent other crashes. Somehow that code had been causing my window to be
> black since 902fe10https://github.com/viciious/qfusion/commit/902fe10ff1b448f0f0af285f6fecacbfb4e7de87.
> The fact that it crashed now might be related to that first note.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/25#issuecomment-24932915
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
As for the GLSL stuff in r_program.c, please launch the game with console
logging enabled, you may see some errors spewed by the compiler..

2013/9/23 Victor Luchitz vluchits@gmail.com

> Pushed a somewhat less intrusive possible fix, please check it out.
> 
> 2013/9/23 Gerco van Heerdt notifications@github.com
> 
> > Possible fix: hettoo@c2b3ddehttps://github.com/hettoo/qfusion/commit/c2b3dde5e5da6c9937ee32edb467d500c097d7cc
> > Note that I had to remove the x11display->dpy = NULL from VID_Sys_Init
> > because VID_WndProc isn't called yet.
> > Also note that I had to remove the #version stuff from r_program.c to
> > prevent other crashes. Somehow that code had been causing my window to be
> > black since 902fe10https://github.com/viciious/qfusion/commit/902fe10ff1b448f0f0af285f6fecacbfb4e7de87.
> > The fact that it crashed now might be related to that first note.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/25#issuecomment-24932915
> > .
> 
> ## 
> 
> Best regards,
>  Victor Luchitz

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
ye, black screen, but i can hear ingame sounds. "as for GLSL stuff" here is console output: http://yadi.sk/d/MfCFOcKM9mce7

btw i've tried hettoo's https://github.com/hettoo/qfusion/tree/x11fix, everything seems fine, no black screen)

**Comment by viciious** [comment]
Dunno why but this is a manifestation of issue #13, which seems to have not been really fixed for NVidia cards. I'm going to reopen #13 and close this issue if hetto confirms the X11 crash is now gone.

**Comment by hettoo** [comment]
That fix looks much better. No crash indeed.
Although it somehow doesn't crash on it anymore, don't forget to remove this duplicate %s\n here: https://github.com/viciious/qfusion/blob/master/source/ref_gl/r_program.c#L381

**Comment by viciious** [comment]
Thanks!
