### ISSUE TITLE
Update to Angelscript 2.28.x

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#27]
http://www.angelcode.com/angelscript/

**Comment by viciious** [comment]
Updated to Angelscript 2.28.0 in commits 72cf3de3d898b196e269b12855914e1df79052aa and 1a2d2214a0e92f46e1fb9d36f0fd35c7025f7fca

**Comment by hasufell** [comment]
OT: is it possible to unbundle angelscript? I'v tried that on warsow-1.02 once and it broke all kinds of stuff.

**Comment by viciious** [comment]
The git stuff here is in no way meant to be compatible with warsow 1.02/1.03

2013/11/9 Julian Ospald notifications@github.com

> OT: is it possible to unbundle angelscript? I'v tried that on warsow-1.02
> once and it broke all kinds of stuff.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/27#issuecomment-28125800
> .

## 

Best regards,
 Victor Luchitz

**Comment by hasufell** [comment]
right, but that doesn't answer my question which is: is angelscript here modified.

**Comment by viciious** [comment]
The original question looked somewhat different to me. What is it that you
really want? I'm not following you, sorry.

2013/11/9 Julian Ospald notifications@github.com

> right, but that doesn't answer my question which is: is angelscript here
> modified.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/27#issuecomment-28134742
> .

## 

Best regards,
 Victor Luchitz

**Comment by hasufell** [comment]
https://github.com/viciious/qfusion/tree/master/libsrcs/angelscript/sdk

you bundle angelscript. The question is if it can be unbundled: as in... use the SYSTEM version.

**Comment by viciious** [comment]
No, not really.

2013/11/9 Julian Ospald notifications@github.com

> https://github.com/viciious/qfusion/tree/master/libsrcs/angelscript/sdk
> 
> you bundle angelscript. The question is if it can be unbundled: as in...
> use the SYSTEM version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/27#issuecomment-28134948
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Resolved.
