### ISSUE TITLE
Question: port other Q2 based games through C++ plugin interface?

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#286]
As by the feature list:
"C/C++ mods (plugins) can ship new gameplay features while maintaining compatibility with the core"

Is this somehow still similar to vanilla Quake2 mods or game-play source modifications?

Could one for example relatively easily port over the turn-based combat etc. from UFO:AI (http://ufoai.org)?

What about the in-game level/terrain editor or the bullet physics from Ya3dag ( http://www.ya3dag.de/ )?

Just a general question ;)

**Comment by viciious** [comment]
No.
