### ISSUE TITLE
rotationbone head not working

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#287]
In theory the head movement should also follow the mouse input and everything seems to be setup correctly in the animation.cfg for the Padpork model, however only the torso moves on mouse input, not the head.

Which my limited coding skills I would guess in 
https://github.com/Warsow/qfusion/blob/master/source/cgame/cg_pmodels.cpp 
lines 1259ff the relevant code lies, but while the comment mention the head too, it only refers to UPPER in the code. But maybe I am wrong.

**Comment by viciious** [comment]
> for( i = UPPER; i < PMODEL_PARTS; i++ )

also includes HEAD

**Comment by poVoq** [comment]
Fine, you convinced me ;) But the head movement is only on one axis.
