### ISSUE TITLE
rotationbone upper only working on one axis (up-down)

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#288]
The animation code that blends mouse input with player-model animation seems to be only partially working:

https://github.com/Warsow/qfusion/blob/master/source/cgame/cg_pmodels.cpp

It bends the torso according to mouse-input but only along one predefined axis (up-down), while normally it should also follow the axis left-right to some limited extend. There seem to be some provisions for that lines 920ff, i.e. that the torso should only move .25 and the head 0.5 or so, but sadly my limited coding skills do not give me a clear picture on what is happening there.

**Comment by poVoq** [comment]
Also see:
https://github.com/Warsow/qfusion/issues/289

**Comment by viciious** [comment]
poVoq, please stop spamming us with your feature requests. We don't take them.

**Comment by poVoq** [comment]
Hmm, this would be a bug report no? Because looking at everything it seems like the functionality is there, just not working correctly.

**Comment by viciious** [comment]
The HEAD rotation is applied as well, but only when the player is moving.

**Comment by poVoq** [comment]
Ok, I double checked in game, and you are right... however also only on the up-down axis which makes it very hard to see, and normally the idea behind this feature is to have it (primarily) follow the left/right axis.
