### ISSUE TITLE
Allow for toggling rotationbone axis for Blender3D exported models

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#289]
See issue outlined here:
https://www.warsow.gg/forum/thread/15519/4

I think the relevant code lies in 
https://github.com/Warsow/qfusion/blob/master/source/cgame/cg_pmodels.cpp

It seems like there is a hard-coded interpretation of rotation axis that corresponds to an model exported from 3DSMax but gets it wrong on a Blender3D .iqm export. I think this is because Blender uses different axis internally.
The result is that the mesh bends (on mouse input) its torso along the left-right axis instead of as intended (and working in the original tris.iqm) along the up-down axis.

As just changing the axis in the code would break all the current models, there needs to be a sort of toggle in the animation.cfg that allows to toggle the axis when the .iqm has been exported from Blender3D. My suggestion would be to add a new parameter in the animation.cfg after the for example _rotationbone upper "Bip01 Spine1"_ for X/Y/Z or so so that one can define the up-down roll axis.
In Blender the axis would be "Y" (x is forward, y is left and z is up in Blender). I think qfusion currently takes "X" as default.

**Comment by viciious** [comment]
> In theory the head movement should also follow the mouse input and everything seems to be setup correctly in the animation.cfg for the Padpork model, however only the torso moves on mouse input, not the head.
> Which my limited coding skills I would guess in https://github.com/Warsow/qfusion/blob/master/source/cgame/cg_pmodels.cpp#1259 the relevant code lies, but while the comment mention the head too, it only refers to UPPER in the code. But maybe I am wrong.
