### ISSUE TITLE
PrintScreen saves a screen from the past on Windows

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#290]
Preconditions: 
cg_showTimer 1 (time goes down from 10:00 to 00:00)

1) Create a match (i.e. a duel with bot)
2) Press F4 to get ready and wait for 20-30 seconds (so warmup ends, and the match starts)
3) Press PrtSc (i.e. ingame clock shows 9:40)
4) ALT+TAB from the game and paste your screenshot somewhere

Result: screenshot shows the clock with the time from the past (i.e. 9:49)

Expecting result: screenshot shows the clock with the ingame time of pressing PrtSc (i.e. 9:40)

Comment: that bug report only shows a strange logic of saving screenshot from the game with PrtSc, while actually it can be reproduced anywhere, but it is harder to notice.

**Comment by Triang3l** [comment]
PrintScreen never really works with fullscreen games, graphics cards don't even have to send the resulting image to window compositing.

**Comment by viciious** [comment]
Not an engine bug
