### ISSUE TITLE
Conform to XDG Base Directory Specs

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#298]
See https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.8.html
- Use $XDG_DATA_HOME or $HOME/.local/share for user's homedir.
- Use $XDG_CACHE_HOME or $HOME/.cache for cache files.

**Comment by Triang3l** [comment]
Are these properly defined in major distros?

**Comment by viciious** [comment]
Even if they are not, the spec explicitly defines fallback paths

**Comment by viciious** [comment]
98ece3f
