### ISSUE TITLE
typo in game/g_weapon.cpp

### ISSUE THREAD

**Issue by Vectory** [Qfusion/qfusion#30]
hi, might wanna fix this ;D

--- a/source/game/g_weapon.cpp
+++ b/source/game/g_weapon.cpp
@@ -113,7 +113,7 @@ static void W_Fire_Lead( edict_t *self, vec3_t start, vec3_t
 }
 #endif

-#define DIRECAIRTHIT_DAMAGE_BONUS 0
+#define DIRECTAIRHIT_DAMAGE_BONUS 0
 #define DIRECTHIT_DAMAGE_BONUS 0

**Comment by viciious** [comment]
Fixed.
