### ISSUE TITLE
Important game code is not reachable during execution

### ISSUE THREAD

**Issue by dnk777** [Qfusion/qfusion#303]
While trying to hack into AI code to make some improvements, I has been stopped by the fact that this condition is never satisfied.
https://github.com/Warsow/qfusion/blob/master/source/game/ai/ai_class_dmbot.cpp#L683

Looks like `GClip_FindRadius` never returns projectiles.

If you print `target->classname` of each found entity, you get following output:

> Target classname: func_plat
> Target classname: trigger_push
> Target classname: func_door
> Target classname: bot
> Target classname: func_door
> Target classname: bot

I use the actual head of the master branch.
I tried to run both listen and dedicated servers. 
I can't fix it since I do not know the whole game codebase well.

**Comment by dnk777** [comment]
Looks like I have found why `GCLip_FindRadius` never returns projectiles:
`if( check->s.solid == SOLID_NOT )
            continue;`
https://github.com/Warsow/qfusion/blob/master/source/game/g_clip.cpp#L1179
SVF_PROJECTILE "sets s.solid to SOLID_NOT for prediction"
https://github.com/Warsow/qfusion/blob/master/source/gameshared/q_comref.h#L255

I have a question:
If I just iterate over array of all edicts (up to `MAX_EDICTS=1024`) checking whether it is a nearby projectile of needed type, does it cause a performance impact compared to use of `GClip_FindRadius`? Its code looks complex and full of branches.

**Comment by viciious** [comment]
Imo the best possible solution is to make a specialized version of GClip_FindBoxInRadius4D that'd work for projectiles too.

**Comment by hettoo** [comment]
Fixed in #339.
