### ISSUE TITLE
Allow to use setColor on drawPlayerName in HUD

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#304]
Currently there is no way to set a custom color for a player name, as setColor doesn't work on drawPlayerName, So in result it makes following case possible, where player name can be barely visible on the background.
![image](https://cloud.githubusercontent.com/assets/4707112/13411193/e8e93a44-df4c-11e5-894e-ce9bb0181140.png)
The solution can be allowing to use setColor/setColorToTeamColor on drawPlayerName.

**Comment by viciious** [comment]
Doesn't make sense to me at all.

**Comment by Triang3l** [comment]
I guess @adem4ik wants a variation of `drawPlayername` that ignores color codes.

**Comment by viciious** [comment]
On a side note, the "Фра" column title looks totally gay btw.

**Comment by adem4ik** [comment]
Makes sense for HUD scripters (me :b). Idea is to force the color on player names, it is useful to avoid such situations as shown above.

With forcing setColor/setColorToTeamColor on drawPlayerName it would be possible:
1) To apply whatever color is needed, i.e. white text on the black background
2) To apply team color to player name, that can be useful for spec hud to see what team player belongs to
3) To make shadows/outlines for the player names by duplicating player name with required color

also clan name color can be forced inside HUD, so not having the same possibility on the player name seems like absence for me.

**Comment by adem4ik** [comment]
Implemented in bff1d3b
