### ISSUE TITLE
Add unit testing support in the project

### ISSUE THREAD

**Issue by dnk777** [Qfusion/qfusion#308]
Lauching a game under debugger and trying to trigger all cases in game is an infinite boredom. Most of code I wrote (and not only too) may be tested independently of a game. I can't do this request:
1. I am not a project owner to make such important decisions that touch the entire project.
2. I am not an (active) C++ developer, so I do not know common tools well.

**Comment by viciious** [comment]
I simply don't have time for this. Nor interest.

**Comment by viciious** [comment]
Neither I'm familiar with unit testing frameworks for C or C++

**Comment by viciious** [comment]
There's Travis CI that integrates with github repositories and where we could theoretically run small unit test programs but coding integration tests and client-server tests and certainly rendering tests is probably a task too complex and unrewarding for undertaking.

**Comment by viciious** [comment]
Mission partly accomplished:
https://travis-ci.org/Qfusion/qfusion
https://ci.appveyor.com/project/viciious/qfusion

**Comment by viciious** [comment]
https://travis-ci.org/Qfusion/asprogs

**Comment by viciious** [comment]
I believe this is the most I can do at this moment. A better documentation and sdk are of higher priority anyway.
