### ISSUE TITLE
AddressSanitizer results

### ISSUE THREAD

**Issue by dnk777** [Qfusion/qfusion#309]
AddressSanitizer should be set up as described in https://gist.github.com/kwk/4171e37f4bcdf7705329.
Don't try to link address sanitizer statically to executable unless you do it for each loaded library too (I spend a lot of time on Linux trying to figure out why "ref_gl" can't be loaded).

**Comment by dnk777** [comment]
This bug may be triggered occasionally on startup
https://gist.github.com/dnk777/21da9d15d345b78d7193

**Comment by dnk777** [comment]
Try to load wdm4, wca1 in botmatch
https://gist.github.com/dnk777/79e68308f88a02de7c34

**Comment by dnk777** [comment]
Try to load wdm4, wca1 in a botmatch
https://gist.github.com/dnk777/211ea657da4e5b846713

**Comment by viciious** [comment]
Thanks! I will look into this asap.

**Comment by viciious** [comment]
Fixed.
