### ISSUE TITLE
[Win] Can't minimize window by clicking icon on the task bar

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#310]
Preconditions: Windows 10, game is started in windowed mode

1) Press minimize button at window border (window gets minimized)
2) Press Warsow icon in the task bar (window gets maximized)
3) Press Warsow icon in the task bar once more

Result: Window gets maximized (there is no matter if Warsow was minimized or maximized before)
Expected result: Window should be minimized (if it was maximized before)

Video: https://youtu.be/J0tDiNh8duk

**Comment by viciious** [comment]
Fixed in 4f253c0
