### ISSUE TITLE
Q3 map with different item layouts and gametypes

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#317]
I'm gonna use **oxodm25** which is a port of QL'c Campgrounds for Q3 as it's easier to share it of me - https://www.dropbox.com/s/8neqe75q9jbm5r2/map_oxodm25.pk3 . Anyway you can repeat the same with Q3's **pro-q3dm6** from _Quake 3 Arena\baseq3\pak0.pk3_ or **campgrounds** from Steam\steamapps\common\Quake Live\baseq3\pak00.pk3.

Duel:
![wsw_160319_111934](https://cloud.githubusercontent.com/assets/4707112/13897533/c8cb5a5e-edc4-11e5-89d0-e37088ace4e6.jpg)
As you can see on this pic, there is extra YA at the same place with RA, and extra LG on PG.

DM:
![wsw_160319_111947](https://cloud.githubusercontent.com/assets/4707112/13897535/d0e4cf0e-edc4-11e5-88d2-b4bec819b31a.jpg)
There should be Quad instead of MH, overall it is fine.

FFA:
![wsw_160319_111956](https://cloud.githubusercontent.com/assets/4707112/13897537/d702a528-edc4-11e5-9efb-6041458ec3ca.jpg)
This one has everything, it is like a mix of duel and tdm, while it should be the same as DM but w/o ammos

TDM:
![wsw_160319_112042](https://cloud.githubusercontent.com/assets/4707112/13897540/de644bf0-edc4-11e5-98ac-4806e5c9b5b0.jpg)
The only gametype which is fine.

**Comment by viciious** [comment]
Examining the .bsp file has revealed three entity spawn keys used to control gt-specific spawn process: notfree, notteam, notsingle.

This is how we handle them: https://github.com/Warsow/qfusion/blob/master/source/game/g_spawn.cpp#L199

**Comment by viciious** [comment]
@adem4ik 01bacf39a0a92b2ca73960ba008c68e4ec5f05fb

**Comment by hettoo** [comment]
I think you meant https://github.com/Warsow/qfusion/commit/01bacf39a0a92b2ca73960ba008c68e4ec5f05fb? :)

**Comment by viciious** [comment]
yes, thanks

**Comment by adem4ik** [comment]
Results of testing changes:

Duel:
![wsw_160319_143827](https://cloud.githubusercontent.com/assets/4707112/13898390/b078134a-ede0-11e5-80f4-92ba5fa684d3.jpg)
Extra armors are fixed, but there is still extra LG on the same place with PG

DM:
![wsw_160319_143854](https://cloud.githubusercontent.com/assets/4707112/13898391/b07857e2-ede0-11e5-9d86-60f0cb85375b.jpg)
Nothing has been changed here, it still needs Quad instead of MH.

FFA:
![wsw_160319_144218](https://cloud.githubusercontent.com/assets/4707112/13898398/d2ad5bf0-ede0-11e5-8262-ea10fb0bee5f.jpg)
Extra armors are fixed, but it needs Quad instead of MH.

TDM
![wsw_160319_144108](https://cloud.githubusercontent.com/assets/4707112/13898392/b07888a2-ede0-11e5-98a9-47149dc4c1d3.jpg)
It is broken now, but it was fine before: it should have LG w/o PG, YA instead of RA and Quad instead of MH

**Comment by adem4ik** [comment]
also seems like there are typos in https://github.com/Warsow/qfusion/blob/master/source/game/g_misc.cpp

> //notduel : when set to 1, entity will not spawn in "Teamplay" and "CTF" modes. (jaltodo)

should be

> //notduel : when set to 1, entity will not spawn in "Duel" mode.

**Comment by viciious** [comment]
`{
"notsingle" "1"
"origin" "-576 -256 60"
"classname" "item_quad"
"notfree" "1"     
}`

Quad can't spawn in DM/FFA because of the "notfree" and "notsingle" keys.

**Comment by viciious** [comment]
I got no idea how QL handles the "notsingle" key.

**Comment by hettoo** [comment]
It seems notsingle is supposed to disable the entity in single player games, e.g. in ioq3: https://github.com/ioquake/ioq3/blob/master/code/game/g_spawn.c#L410.

Since "we don't have proper single player mode yet" (or rather no flag for it I think), this return false that disables the entity in any gametype I believe should really not be there: https://github.com/Warsow/qfusion/blob/master/source/game/g_spawn.cpp#L205.
Currently this code pretends any gametype is single player.

**Comment by viciious** [comment]
Yeah, I got confused a bit there, thanks.

**Comment by adem4ik** [comment]
Duel:
![wsw_160320_125951](https://cloud.githubusercontent.com/assets/4707112/13903846/c5c706be-ee9b-11e5-8109-6444032f32fb.jpg)
There is the same situation it was initially before reporting the bug:
- extra YA from TDM on RA place
- extra RA from TDM on YA place
- extra weapons from TDM like LG on PG place

DM:
![wsw_160320_130007](https://cloud.githubusercontent.com/assets/4707112/13903844/c5c449e2-ee9b-11e5-9286-44408430a6c9.jpg)
Seems fine now

FFA:
![wsw_160320_130014](https://cloud.githubusercontent.com/assets/4707112/13903843/c5c3ddb8-ee9b-11e5-863a-8f7bc8b2b2fc.jpg)
Seems fine now

TDM:
![wsw_160320_130023](https://cloud.githubusercontent.com/assets/4707112/13903845/c5c482fe-ee9b-11e5-95ca-39a731600e39.jpg)
Seems fine now

**Comment by adem4ik** [comment]
Also i can test another map now:  https://www.dropbox.com/s/s81yy6wy6yypajf/map_oxodm25a.pk3?dl=0 which is Campgrounds Intel, it has a bit different issues with items' layout:

Duel: 
![wsw_160320_131515](https://cloud.githubusercontent.com/assets/4707112/13903900/25658d78-ee9e-11e5-83ee-a5a634e7bf53.jpg)
It has armors and weapons from TDM, same as oxodm25
- extra YA from TDM on RA place
- extra RA from TDM on YA place
- extra weapons from TDM like LG on PG place

DM:
![wsw_160320_131530](https://cloud.githubusercontent.com/assets/4707112/13903901/25684234-ee9e-11e5-9deb-9ca3d369ec8a.jpg)
it has extra weapons from TDM and it should has Quad only w/o MH.

FFA:
![wsw_160320_131541](https://cloud.githubusercontent.com/assets/4707112/13903902/25685bc0-ee9e-11e5-9e12-6fe6c2aaf34e.jpg)
FFA should have Quad instead of MH

TDM:
![wsw_160320_131554](https://cloud.githubusercontent.com/assets/4707112/13903903/25688154-ee9e-11e5-86dc-18991c8d09c3.jpg)
it has extra MH on the same place as Quad

**Comment by viciious** [comment]
The second map uses "team" for "tdm", this is not going to work in Warsow.

**Comment by viciious** [comment]
"notfree" now also affects duel, see b7561f4c856e8afba26d53f684ea283a7efc4a12

**Comment by viciious** [comment]
@adem4ik please confirm and close the issue

**Comment by adem4ik** [comment]
Fixed now:

Duel
![wsw_160320_163300](https://cloud.githubusercontent.com/assets/4707112/13904734/439e7274-eebb-11e5-8b94-88f7a43a80b2.jpg)

DM
![wsw_160320_163308](https://cloud.githubusercontent.com/assets/4707112/13904737/43a24548-eebb-11e5-83ef-6eeb50782aae.jpg)

FFA
![wsw_160320_163314](https://cloud.githubusercontent.com/assets/4707112/13904735/439e9bfa-eebb-11e5-88b5-cebbcaa1a37d.jpg)

TDM
![wsw_160320_163322](https://cloud.githubusercontent.com/assets/4707112/13904736/43a23850-eebb-11e5-9a93-3774663044ba.jpg)
