### ISSUE TITLE
[LLVM/Clang] ui/as/asbind.h:248:17: error: 'A' declared as an array with a negative size

### ISSUE THREAD

**Issue by ghost** [Qfusion/qfusion#32]
Build log: http://bpaste.net/show/139617/

Compilation errors out when using llvm/clang (this also present on 1.0.2/3 source).
I change the offender to 1 - 1 to avoid going to -1 just to be able to build the game, I haven't noticed any issues with doing so. Not sure how correct of a fix that really is as this is not my area of expertise.

I've also ran static analyzer over the code and it comes up with ~450 issues so you may be interested in looking in to that at some point in case any are of interest to you, this is the only show stopper in regards to building and running the game on my end though :)

**Comment by viciious** [comment]
I periodically run static analyzer over the code and fix all real issues.
What's left is mostly noise but feel free to post your logs, I'll look at
them.

As for that error, I think you're not supposed to hit that branch of code
in case everything goes fine with the compiler and templates..

2013/10/11 rorgoroth notifications@github.com

> Build log: http://bpaste.net/show/139617/
> 
> Compilation errors out when using llvm/clang (this also present on 1.0.2/3
> source).
> I change the offender to 1 - 1 to avoid going to -1 just to be able to
> build the game, I haven't noticed any issues with doing so. Not sure how
> correct of a fix that really is as this is not my area of expertise.
> 
> I've also ran static analyzer over the code and it comes up with ~450
> issues so you may be interested in looking in to that at some point in case
> any are of interest to you, this is the only show stopper in regards to
> building and running the game on my end though :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/32
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Fixed in commit c63672c41a.

**Comment by ghost** [comment]
Hey sorry for the late reply, I was literally just in the process of creating fresh analyzer logs. They are available here if you get bored and wish to take a look: https://dl.dropboxusercontent.com/u/45656686/static_analysis_results.tar.bz2

Also thank you very much for the proper fix, I can confirm the issue has been resolved.
