### ISSUE TITLE
IG hits only 1st player model

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#320]
IG hits only 1st player, but not anyone after it. Even though its gfx effect seems to go trough. Also EB doesn't have such issue.
https://youtu.be/u4q28Q5rKJc

p.s. sorry for some video artifacts, it is not connected with warsow at all, but a problem of obs for linux

**Comment by viciious** [comment]
Addressed in 2ec31b67436aa18bd950a4d0508d96a9e3c52b3f
