### ISSUE TITLE
Unsupported mouse button on Linux

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#322]
OS: Kubuntu 14.04.4
SDL2 version: 2.0.2
Mouse: a4tech XL-750BH http://www.x7.cn/en/product.asp?id=48

So my mouse has MOUSE1, MOUSE2, one programmable button which is set as MOUSE3, MOUSE3 from wheel, and two side buttons: MOUSE4 and MOUSE5.

Using UI to bind MOUSE4 gives MOUSE8, while binding MOUSE5 gives **sdl_input.c: Unsupported mouse button (button = 9)** in console

It can be related to https://github.com/Warsow/qfusion/pull/299 as in Warsow 2.0 MOUSE4 was recognized as MOUSE6 and MOUSE5 as MOUSE7.

**Comment by hettoo** [comment]
The game has MOUSE1 through MOUSE8, which at the moment are mapped from button codes 1 through 8 in the following order:
1 3 2 6 7 4 5 8
If there is a button 9, it will not be recognized.

Looking at the non-sdl implementation, it maps codes 1 through 10 as follows:
1 3 2 wheelup wheeldown 6 7 4 5 8

In Warsow 2.1 my sidebuttons are MOUSE6 and MOUSE7. Changing to the above 10-button configuration would identify them with scroll up and scroll down...

**Comment by adem4ik** [comment]
In a short my side mouse buttons depending on OS and game version:
- Windows, Warsow 2.0 - MOUSE4, MOUSE5
- Windows, Warsow 2.1 - MOUSE4, MOUSE5
- Linux, Warsow 2.0 - MOUSE6, MOUSE7
- LInux, Warsow 2.1 - MOUSE8, **sdl_input.c: Unsupported mouse button (button = 9)**

**Comment by hettoo** [comment]
We could use this order to make both our mouses work as they should:
1 3 2 6 7 wheelup wheeldown 4 5 8

The question is if there are mouses that emit button = 6 or button = 7 (in 2.1 these are MOUSE4 and MOUSE5), or there will be other complaints. :p
