### ISSUE TITLE
[Linux] Mouse Leaving Window

### ISSUE THREAD

**Issue by Vectory** [Qfusion/qfusion#342]
This is in warsow 2.1 on Debian wheezy with libsdl-2 from a backport repo. The bug might be in earlier releases, too. Can't imagine this is unkown yet.

If in windowed mode or fullscreen with less than the desktop resolution, then the mouse will move over the whole desktop and only get focus when over the game.

Is this a problem with my gfx-card (radeon) or the backported package? I know debian is frequently behind versions. I'm gonna check with a new system soon.

I'd have a look myself, if I found where to start in the code. I had a quick look at the X11 headers in old 0.\* times and don't know what changed. It used to work well ofc so I should try a git bisect maybe?

**Comment by viciious** [comment]
What you're describing sounds like intended behavior if in_grabinconsole is set to 0.

**Comment by Vectory** [comment]
![mbug1](https://cloud.githubusercontent.com/assets/328905/15984763/b6dfca7e-2fd6-11e6-8a46-238048ee999f.png)

nope, in_grabinconsole does not make a difference

**Comment by viciious** [comment]
This totally sounds like a SDL bug. Is it still present/reproducible?

**Comment by Vectory** [comment]
Seems to work in master using debian testing.
I'm sorry that I didn't get back as I said.
