### ISSUE TITLE
Performing skimming produces jerky movement

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#343]
Youtube: https://youtu.be/cFiMR5SSc-s (watch 1080p@60fps)
Source video: https://yadi.sk/i/MGA2yEqSscaew
Binaries: https://github.com/Picmip/qfusion/releases/tag/movement_test
cl_maxfps/r_maxfps: 250

It happens that skimming may conflict with prediction, so in result its performing produces screen shakes. Presented video shows the most prominent screen shakes, even though I do find movement near the walls a little shaky most of the time.

**Comment by viciious** [comment]
Use cg_showMiss 1 to check your prediction hypothesis.

**Comment by adem4ik** [comment]
Here is a video with cg_showMiss 1, tbh I don't know what do those numbers mean
https://youtu.be/Ctghx0hHjD8 (watch the top left corner to see prediction misses)

**Comment by hettoo** [comment]
Thanks for the report and for adding the videos, adem.
At the moment I have little time, but early in July I will try to look at some movement things including this issue. :)

**Comment by hettoo** [comment]
Thanks again. Fixed in #349. :)

**Comment by adem4ik** [comment]
Thank you too :+1: I do confirm the fix.
