### ISSUE TITLE
Weapons not selecting

### ISSUE THREAD

**Issue by hettoo** [Qfusion/qfusion#35]
Somehow I am unable to select (use) all weapons except gunblade, machinegun, plasmagun and lasergun.
Rocketlauncher does select on spawn.

**Comment by viciious** [comment]
Works for me?..

2013/11/7 Gerco van Heerdt notifications@github.com

> Somehow I am unable to select (use) all weapons except gunblade,
> machinegun, plasmagun and lasergun.
> Rocketlauncher does select on spawn.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/35
> .

## 

Best regards,
 Victor Luchitz

**Comment by hettoo** [comment]
Nvm, makedepend issue. The changed weapondef structure must have not gotten through to all objects, recompiling everything fixed it.
