### ISSUE TITLE
Timedemo doesn't count renderer fps

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#350]
Preconditions: there is demo recorded & placed at game/base/demos/ - https://yadi.sk/d/Zkex2bh2t8SGK

1) Apply high+ video profile to get lowest possible fps during benchmarking
2) Type in console: _timedemo 1_
3) Type in console: _demo 1_
4) Wait till demo ends
5) Open console

Result: console shows that demo was played nearly to the maximum possible fps - 900+
Expected result: console shows actual average renderer fps

**Comment by viciious** [comment]
Should be fixed in 8df150b3aad051cb66cbd9daf0fac708beb3598b

**Comment by viciious** [comment]
More fixes in 8480bb6

**Comment by adem4ik** [comment]
Fixes are confirmed
