### ISSUE TITLE
Distortion and water rendering issues

### ISSUE THREAD

**Issue by dnk777** [Qfusion/qfusion#351]
AFAIR the distortion shader that used to render a water works in screen space without checking the depth. This causes objects that are between a distorted surface and a camera to be distorted too.
For example, a RA on wdm5 looked distorted when looking on the sewage water. Looks like a water distortion is turned off completely in 2.0+ (or I just can't figure how to turn it on).

Also light dispersion-aware distortion (different distortion strength for R,G,B) for water should look nice.

**Comment by solidfake** [comment]
I don't even know if distortion is still supported, it hasn't been updated in quite a while since because it caused lighting issues afaik

**Comment by viciious** [comment]
It is supported but was removed from the maps mostly for performance reasons.

**Comment by viciious** [comment]
Also, distortions do not exactly work in screenspace. Each distortion is represented by a separate famebuffer image, each with its own depth.
