### ISSUE TITLE
Build with GAME_MODULES_ONLY flag produce libraries w/o _x86 or _x64 in their names

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#352]
Precondition: Windows OS, Qfusion git repo is cloned, Visual Studio & Cmake are installed

1) Start Cmake, select source code and binaries folders
2) Press Configure, select generator (i.e. Visual Studio 14 2015 Win64) and press Finish
3) Check GAME_MODULES_ONLY and press Generate
![image](https://cloud.githubusercontent.com/assets/4707112/17084718/2792e1e0-51d6-11e6-9396-21f9039fd105.png)
4) Open qfusion.sln inside Visual Studio
5) Build the solution

Result: Libs' names don't have addition like "_x86" or "_x64"
![image](https://cloud.githubusercontent.com/assets/4707112/17084714/0d64cb8a-51d6-11e6-883e-d3c8cc875c57.png)

Expected result: Libs' names have addition like "_x86" or "_x64" according the generator selected on 2) step
![image](https://cloud.githubusercontent.com/assets/4707112/17084715/168955c8-51d6-11e6-9758-52c5cb5c6b4b.png)

**Comment by viciious** [comment]
Fixed in f3b9469fb620f1019d333885d6f96f69253d1905.
