### ISSUE TITLE
R_EndFrame: Assertion `qglGetError() == 0' failed.

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#354]
`glClear()` generates the 0x506 code if the active draw buffer status is not "complete".
https://cgit.freedesktop.org/mesa/mesa/tree/src/mesa/main/clear.c#n176

This code
https://gist.github.com/dnk777/86dba154bd0b95ae4f39d4787f9eb0c0
has following output:

```
====== Warsow Initialized ======
Couldn't execute: autoexec_postinit.cfg
read fbo id: 15, draw fbo id: 15
read fbo attachments:
attachment COLOR0: type 0x1702
attachment DEPTH: type 0x8d41
attachment STENCIL: type 0x0
draw fbo attachments:
attachment COLOR0: type 0x1702
attachment DEPTH: type 0x8d41
attachment STENCIL: type 0x0
Unsupported
Color buffer bit
Depth buffer bit
warsow.x86_64: /home/***/qfusion/source/ref_gl/r_backend.c:***: RB_Clear: Assertion `qglGetError() == 0' failed.
zsh: abort (core dumped)  ./warsow
```

Looks like framebuffer attachment format is not supported.

Result of `RFB_CheckObjectStatus()` is ignored:
 https://github.com/Qfusion/qfusion/blob/master/source/ref_gl/r_backend.c#L654
This branch is selected in `RFB_CheckObjectStatus()`:
https://github.com/Qfusion/qfusion/blob/master/source/ref_gl/r_framebuffer.c#L604

**Comment by dnk777** [comment]
If I print "Complete!" and "Unsupported" in `RFB_CheckobjectStatus()`, output is
https://gist.github.com/dnk777/cd9898b25efa86fabf2b66614fbcc3de
and it crashes

```
**** ~/warsow_21 % ./warsow.x86_64 +set fs_usehomedir 1 +set r_hdr 0 +set r_bloom 0 >wsw.txt 2&>1
zsh: abort (core dumped)  ./warsow.x86_64 +set fs_usehomedir 1 +set r_hdr 0 +set r_bloom 0 > wsw.txt 2&
```

This condition is never satisfied
https://github.com/Qfusion/qfusion/commit/4c8a8a7d2739c96fb1f1c715395e1e1998d4b17a#diff-19220b77c57cf498f15eaffefe6c7779R379

**Comment by viciious** [comment]
Try launching the game with +set gl_ext_texture_float 0 +set gl_ext_texture_sRGB 0

**Comment by dnk777** [comment]
Looks like it works now

**Comment by viciious** [comment]
It works but the underlying issue remains: either your driver is buggy and advertises functionality it can not handle or the engine is missing some runtime checks.

**Comment by dnk777** [comment]
Tell me what GL features you are interested in, and I will check their support in a tiny test app.

**Comment by dnk777** [comment]
I think it should be closed as I never run into this bug (having updated a distro though)
