### ISSUE TITLE
WARNING: shader XXX has a stage with no image: YYY

### ISSUE THREAD

**Issue by dnk777** [Qfusion/qfusion#355]
On branch upstream/master (and mine too) i get these warnings:
https://gist.github.com/dnk777/66c77c35e57d36832c79c8d81b3d6ec8
Visually it looks like some brushes are absent or transparent.

**Comment by viciious** [comment]
Not an engine bug: 8a17adfd.

Besides, you shaders appear to be messed up: textures/wsw_city1/vertex_stepup01_shiny doesn't map any texture from the disk in stock warsow.

**Comment by dnk777** [comment]
I tried to use default 2.1 assets, the only modifications made are required for launching the modified since 2.1 release engine (`ui`, `glsl`, `progs`). And also I wiped `~/.local/share/warsow-2.(0|1)`. Now I am unable to even launch a local game, and the UI background is grey.

https://gist.github.com/dnk777/f17d378c2238cf074095f9ddb251ccaf

So I can't even continue development now.
Looks like assets that the engine expect have been changed since 2.1 release too.

**Comment by dnk777** [comment]
Ok thats a pretty lame bug, the version in upstream was reset to 2.0 after merge. I will supply a patch ASAP.

**Comment by viciious** [comment]
> Using /home/me/.local/share/warsow-2.0 for writing

Why is it using ..../warsow-2.0 as the homedir anyway? Should be warsow-2.1.

It appears that the engine is ignoring pure content in basewsw because of the version mismatch.
Try running cmake with -DQFUSION_GAME=Warsow -DCMAKE_C_FLAGS=PUBLIC_BUILD
