### ISSUE TITLE
Non-zero reference count for some UI object

### ISSUE THREAD

**Issue by dnk777** [Qfusion/qfusion#356]
On branch upstream/master put these lines in 
`libRocket/Source/Code/ReferenceCountable.cpp/~ReferenceCountable()`:

```
ReferenceCountable::~ReferenceCountable()
{
    if (reference_count != 0)
    {
        printf("reference_count: %d\n", reference_count);
        abort();
    }
    ROCKET_ASSERT(reference_count == 0);
    --num_outstanding_objects;
}
```

(ROCKET_ASSERT just prints a warning in console, thats how I spotted it).

Stacktrace and printf output looks like this:
https://gist.github.com/dnk777/b176d22748a08cbea4b6de473e0dc695
Reference count does not depend of count of maps loaded (if any) and always is 2.

**Comment by viciious** [comment]
This is known and harmless.
