### ISSUE TITLE
Which game modules to install

### ISSUE THREAD

**Issue by Vectory** [Qfusion/qfusion#358]
What is required to test builds? I could load a map, but see bad graphic bugs and want to confirm that game files aren't at fault.

1. copy all basewsw/* files from warsow 2.1 into build/base/, but modules_21.pk3 is not needed
2. extracted all the data_*.pk3 files
3. leave libgame*.so and libcgame*.so in base/, which is why the module pk3 shouldn't be copied

I don't know why the last step is different when building warsow 2.1 from source, so that the *.so files have to be deleted instead of module_21.pk3, which caused me some confusion.

Also, I thought it would be good to have instructions here or in the wiki, so I paste different errors that I encountered, to make them available to search.

> WARNING: shader gfx/ui/console has a stage with no image: gfx/ui/console
> WARNING: shader gfx/ui/console has a stage with no image: gfx/ui/console
> ------- UI initialization -------
> LibRocket: WARNING: Unable to open file ui/porkui/cursors/default.rml.
> LibRocket: WARNING: Unable to open file /ui/porkui/index.rml.
> DocumentLoader::loadDocument failed to load /ui/porkui/index.rml

> ERROR: 'Default Player Model'(bigvic): Skin (models/players/bigvic/default) failed to load

> ERROR: Client game is version 98, not 99

**Comment by viciious** [comment]
Hi,

it's hard to tell what's going wrong with graphics by description alone, a screenshot would help. The steps you listed appear to be correct. Except that I would also add config.cfg to the exception list in step1. That might be the reason for some of the errors you listed above.

Also, make sure you're extracting all data_*.pk3 files into base/ itself, not a subdirectory of base/.

**Comment by viciious** [comment]
More steps:

5. change current directory to base/
4. remove glsl/, git clone https://github.com/Qfusion/glsl
5. remove l10n/, git clone https://github.com/Qfusion/l10n
6. remove huds/, git clone https://github.com/Qfusion/huds
7. remove progs/, git clone https://github.com/Qfusion/asprogs as "progs"
8. remove ui/, git clone https://github.com/Qfusion/rocketui as "ui"

**Comment by Vectory** [comment]
Of course, the old configs might not work, what a newbie mistake. Your last post ultimately fixed it.

Now with new glsl etc., the old configs even seem to work in first test.
