### ISSUE TITLE
Engine draw only normal map

### ISSUE THREAD

**Issue by ice-cr3am** [Qfusion/qfusion#360]
![default](https://cloud.githubusercontent.com/assets/15231426/21554068/91fd858a-ce1d-11e6-942b-22ea1504099d.png)

Engine don't warning about texture in console

**Comment by viciious** [comment]
You do not provide enough information. Post your shader, config, console log, everything that might help to solve the problem.

Besides, have you tried loading the map with developer 1?

**Comment by viciious** [comment]
Closing as the reporter failed to provide additional information.
