### ISSUE TITLE
Player name is connected to the last playerID after rewinding demo

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#361]
Possible cases that were found in Warsow 2.1, unfortunatly I can't check it in the current Qfusion:

**Case#1**
Preconditions: there is a demo with someone who has start to watch

the match and disconnected in the middle of it (let it be PlayerName)
1) Open the demo (scoreboard shows PlayerName among Spectators)
2) Jump to that moment when PlayerName has disconnected (scoreboard shows "badname" for a while among Spectators instead of PlayerName)
3) Jump to the start of the demo

Result: PlayerName is replaced by "badname" till the PlayerName disconnects from the server

Screenshots:
1) ![wsw_170111_033134](https://cloud.githubusercontent.com/assets/4707112/21829324/ca79b8da-d7ae-11e6-8e11-b2f607c63101.jpg)
2) ![wsw_170111_033218](https://cloud.githubusercontent.com/assets/4707112/21829332/d10a1488-d7ae-11e6-994a-a69fe63c1690.jpg)
3) ![wsw_170111_033230](https://cloud.githubusercontent.com/assets/4707112/21829339/d4ef388a-d7ae-11e6-953a-8417eddb184c.jpg)

**Case#2**
Preconditions: there is a demo of team match, where one of the players has disconnected in the middle of the match (let it be PlayerA), and a new player connected to the match after the 1st one (let it be PlayerB). Typical situation of pickups when someone needs to leave and another one subs him.

1) Open the demo (scoreboard shows PlayerA name)
2) Jump to that time when PlayerB connected to the match (scoreboard shows PlayerB name)
3) Jump to the start of the demo

Result: PlayerA name is replaced by PlayerB name.

**Comment by viciious** [comment]
Try this branch: https://github.com/Qfusion/qfusion/tree/playerinfos_reset

**Comment by adem4ik** [comment]
I've tested the 1st case
[2017-01-20_21-41_duel_rekt_playerBvsplayerB1_auto3534.md1001.zip](https://github.com/Qfusion/qfusion/files/720124/2017-01-20_21-41_duel_rekt_playerBvsplayerB1_auto3534.md1001.zip):
1. Open the demo (scoreboard shows "spec" among Spectators)
2. Jump to that moment when spec has disconnected (scoreboard shows "badname" for a while among Spectators instead of spec)
3. Jump to the start of the demo

Result is different now but still not as expected: "Spec" is replaced by "" (nothing) till the spec disconnects from the server

Screenshots before and after the jump:
![wsw_170120_214524](https://cloud.githubusercontent.com/assets/4707112/22159407/2fbdd0c0-df5a-11e6-86b0-f27a3df38c1f.jpg)
![wsw_170120_214532](https://cloud.githubusercontent.com/assets/4707112/22159411/3306bce2-df5a-11e6-9a89-24494a94dcff.jpg)

**Comment by adem4ik** [comment]
2nd case isn't fixed:
I've recorded a demo, so you can try by your self: 
[2017-01-20_21-51_duel_rekt_playerBvsplayerB1_auto7175.md1001.zip](https://github.com/Qfusion/qfusion/files/720125/2017-01-20_21-51_duel_rekt_playerBvsplayerB1_auto7175.md1001.zip)
1) Open the demo & press tab -> Spectator has "spec1" name
3) Jump to the end of the demo -> Spectator has reconnected with another name "spec2"
4) Jump to the start of the demo:
Result: Spectator name is shown as "spec2" instead of "spec1"

**Comment by viciious** [comment]
Fixed in d72f48330a80460f8c31845a7a4b35b32c10b8db

**Comment by viciious** [comment]
Although this is now technically fixed, I'm not entirely happy with the solution

**Comment by viciious** [comment]
After pondering at this for some more, I've decided to keep the current fix in place.
