### ISSUE TITLE
Out-of-bounds array access due to extra console colors

### ISSUE THREAD

**Issue by dnk777** [Qfusion/qfusion#362]
The engine has `^8`, `^9` colors, these colors are unmatched in ANSI console colors set. The code 

https://github.com/Qfusion/qfusion/blob/master/source/unix/unix_console.c#L52

does not take these colors into account, and this leads to the mentioned out-of-bounds array access,  and AddressSanitizer gets triggered instantly. I am not sure what is a proper way to represent the engine colors missing in the ANSI colors set.

**Comment by viciious** [comment]
The code line
`static int q3ToAnsi[ 8 ] =`
should read as
`static int q3ToAnsi[ MAX_S_COLORS ] =` instead.

**Comment by dnk777** [comment]
I mean its unclear what representation should be used for these two extra colors

**Comment by viciious** [comment]
I'm assuming that the original code assumed the zero-fill (COLOR_WHITE) would work for all extra colors :)

**Comment by viciious** [comment]
Fixed in b587fc6. Thanks.
