### ISSUE TITLE
FPS limit when the window is out of focus

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#364]
When the window isn't in fullscreen mode and it goes out of focus FPS gets limited by 24. That behavior seems quite uncomfortable & unpleasant as for streamers as for players who use borderless mode.

Let me explain why:
1) For the streamers: nowadays people use at least 60fps for streaming their games, as it provides quite smooth and eye friendly experience for their viewers. 30fps or 24 fps is just not enough today.
Usually when streamer wants to cast something he starts the game in windowed mode. During the stream he has to handle a lot of things like chats, tourney brackets, or any other apps besides the game itself. So when he decides to switch the windows QFusion limits FPS to 24, and viewers start to watch slideshow.
2) Similar case happens for borderlerss mode fans, as after they switch the window, QFusion stays in the background and limits FPS to 24, which seems like a slideshow too.

My ideas: 
a) 24 FPS limit for window out of focus can be removed at all, but it may stay only for minimized window.
b) There can be 60 FPS limit instead of 24 FPS. But that's quite temporary solution, since 120/140/240 Hz monitors are becoming more and more popular nowadays, and there may appear 120 FPS streams soon too.

**Comment by viciious** [comment]
Hopefully resolved in 87542022838a10bd2d7b831e3e6e6e0f3add395f.

**Comment by adem4ik** [comment]
Thanks, I'll check it on Windows and Linux

**Comment by adem4ik** [comment]
Tested Windows (non SDL2 build) & Linux. There is no 24 FPS can for window out of focus. Thanks.
