### ISSUE TITLE
Apply blur effect to the background map in the main menu

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#365]
So I'm just requesting a blur effect on the background map in the main menu as it done in post match status in game. Why? Cause it would make menu's text more readable and its checkboxes more noticeable 👍 

Just take a look on comparison:
![1](https://cloud.githubusercontent.com/assets/4707112/22221605/3638cff2-e1cd-11e6-9a88-1f1c5fcb2b80.png)
![2](https://cloud.githubusercontent.com/assets/4707112/22221610/39f564ca-e1cd-11e6-9134-51bc162fafe6.png)

**Comment by viciious** [comment]
Should blur also be applied to HUD elements?

**Comment by adem4ik** [comment]
Yes, it would be logically to apply the same blur to the **ingame map and HUD elements** if the main menu is open.

Or, if it's hard to implement blur on HUD elements, HUD can be just hidden if the main menu is open.

The only case I'm afraid of is the demo play menu, it should be checked that blur effect doesn't affect on the map/HUD if the demo menu is open.

**Comment by viciious** [comment]
Obviously the effect should only work for fullscreen menus.

**Comment by viciious** [comment]
I'll some kind of option to enable the blur effect from the menu although I believe it's a wrong solution to your problem. Here's how Deus Ex: Mankind Divided works around the readability issue:

http://www.mobygames.com/images/shots/l/858795-deus-ex-mankind-divided-windows-screenshot-main-menu.jpg

https://www.overclock3d.net/gfx/articles/2016/08/18042026321l.jpg

**Comment by viciious** [comment]
Fixed in 6357820351d7545d06adb04a3dbec1117d899f43. Use the "blur" widget/tag for the fullscreen blur effect in UI.

**Comment by viciious** [comment]
http://imgur.com/a/QD1mV

**Comment by adem4ik** [comment]
Thanks, it looks pretty good.
