### ISSUE TITLE
angelscriptd.dll is reported missing from both debug and release executables

### ISSUE THREAD

**Issue by 0nix** [Qfusion/qfusion#368]
The debug and release builds of qfusion crash at startup with the following message: "The program can't start because angelscriptd.dll is missing from your computer. Try reinstalling the program to fix this problem." Qfusion then starts a window, and throws another error: "Could not find any shaders!"

The strange thing is that angelscriptd.dll is on the libs folder of both Debug and Release.

**Comment by viciious** [comment]
qfusion uses static linking for all third-party libraries. you must be doing something wrong.
