### ISSUE TITLE
Unknown package type '/tmp/tmp.gly4gcgGB4', exiting

### ISSUE THREAD

**Issue by space-potato** [Qfusion/qfusion#369]
I'm using the guide "compile on Linux" of the Wiki and, during the first series of commands:

sudo apt-get update ; sudo apt-get install git gdebi-core;
FILE=`mktemp`; wget "https://github.com/Picmip/qfusion/raw/master/debian/qfusion-dev_0.4_all.deb" -qO $FILE && sudo gdebi $FILE; rm $FILE

when I get at "sudo gdebi $FILE" I get the error "Unknown package type '/tmp/tmp.gly4gcgGB4', exiting".. do you have any idea of what this means?

I'm using Debian 9, by the way

**Comment by viciious** [comment]
Apparently newer gdebi versions perform file extension check on the input

**Comment by viciious** [comment]
Please try the updated guide:
https://github.com/Qfusion/qfusion/wiki/Compiling-on-Linux

**Comment by space-potato** [comment]
Yes, now it seems to be working, thanks!
