### ISSUE TITLE
Warsow textures won't load in netradiant

### ISSUE THREAD

**Issue by arachide** [Qfusion/qfusion#370]
Hi, sorry if this may not be a "bug", but there really isn't a support forum and I thought you could have been a more appropriate person to ask, since you are probably directly involved with warsow and netradiant itself.

I have been able to install netradiant and I have downloaded the warsow source code (the archive "source + tools" on the website). I used that folder as a path for netradiant's warsow config, but the textures are not loaded (there is a subfolder called "textures", in the warsow folder) and all I see is only the pre-defined invisible texture and nothing else (I think there should have been a small menu with all the textures' folders to choose from, but nada).

I don't see any way to manually import textures in the project, I can only import maps, but they of course are without textures. Am I doing something wrong?

**Comment by viciious** [comment]
Hi,
I think what you should do is install netradiant from sdk archive and set the engine path to Warsow installation path - the one which contains basewsw directory, not the sdk package!

**Comment by arachide** [comment]
Ok, now it works! at first it didn't work.. then I switched layout to 4-panel-view; got an error when tried to open the texture panel; re-switched the default layout and now I have the texture panel with all the texture  (some of them are missing, but that's probably another story)

Thanks!
