### ISSUE TITLE
Post match countdown "Waiting... %s" is blinking

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#374]
1) Start a duel game (with the bot in example)
2) Win the match and wait till the game ends

Result: watch the video
https://youtu.be/JgQcY6IOb_Y
Expected result: "Waiting... %s" should be shown right along.

**Comment by viciious** [comment]
Fixed in 1cccbf448e876032bcae0f5aea9b98800652a4b4

**Comment by adem4ik** [comment]
tested, fix was confirmed. thanks!
