### ISSUE TITLE
Enemy LG beam isn't shown

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#375]
Video shows it better:
https://youtu.be/84BVEqPTjcE

**Comment by dnk777** [comment]
Please describe the environment where you have tested it. Is the beam shown sometimes? I thought at the first look a world beam is not shown for its owner, but you have two client instances connected which have different numeric id (`playerNum`).

**Comment by adem4ik** [comment]
Environment: windows 10 x64,  artifacts from appveyor, wdm5, local server made by "/map wdm5" inside console. 2nd player has connected to the local server by "/connect 127.0.0.1".

**Comment by dnk777** [comment]
I have tested vanilla 2.1 build and a build of my current bot development GOAP branch which has diverged in October 2016,  and everything is shown properly. @viciious is it the new netcode issue?

**Comment by adem4ik** [comment]
it might be regression of https://github.com/Qfusion/qfusion/commit/82ce50b5a437020c8dba83c4e78ee2fa3a098e6b

**Comment by viciious** [comment]
Fixed in 65d7cce192ab5fde0132c7edf4b10151d0fba03e

**Comment by adem4ik** [comment]
checked in local match with bot, enemy LG is drawn now.

Thanks!
