### ISSUE TITLE
Incorrect physics of Grenades on QuakeWorld maps

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#377]
It seems like grenades think that some walls and floors are longer than they actually are. Also there are some funny stacks happens in windows and arks.
https://youtu.be/U7a1orciB3M
[qw_maps.zip](https://github.com/Qfusion/qfusion/files/888762/qw_maps.zip)

**Comment by viciious** [comment]
Q1 allows collision objects of only three sizes (hulls): zero, player and ogre/shambler. Even rottweiler monsters are effectively the same size as the player.

The increase of grenade size in commit 364473b7b457b850aa7a439aeef68355e6d6c785 resulted in grenades being the size of dogs far as collision goes.

My fix suggestion is to reduce the size to +-2 in all dimentions for grenades so they would be treated as zero hull size objects in Q1 maps.

**Comment by viciious** [comment]
Fixed in f32b890f875b60a20aa2ff95a241465a680294c1

**Comment by adem4ik** [comment]
Previous fix didn't work

Reducing size to +-1 works - https://github.com/Qfusion/qfusion/pull/378
