### ISSUE TITLE
Hit sound from the splash damage gets skipped

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#382]
1) Download attached .aas and drop it to /base/maps - [rekt-aas.zip](https://github.com/Qfusion/qfusion/files/901012/rekt-aas.zip)
2) /map rekt
3) /callvote numbots 1
4) /botnotarget
5) wait till the bot stops
6) hit some splash damage by RL or GL

Result: hit sounds aren't played everytime, it may be skipped.
Watch this video - https://youtu.be/hkQlKShaRWo

**Comment by viciious** [comment]
I can't reproduce this..

**Comment by adem4ik** [comment]
I can't reproduce it anymore too. Closed.
