### ISSUE TITLE
Support environmental sound effects

### ISSUE THREAD

**Issue by dnk777** [Qfusion/qfusion#391]
Implementing this thing is really interesting to me, and would be cool (since poor sfx both from assets and technology point of view are the most notable flaw of the existing game). There is a support for these effects at least from OpenAL side (including the software version). The absence of the environment information for reverberation/obstruction is not a significant issue. Since we have cheaper traces now, it can be sampled in runtime. I have already figured out ways of reconstruction of an environment, and how to achieve a good performance (it is an order of magnitude easier than everything related to AI).

The only concern is that it has to be done in main client thread (somewhere in `SF_Update`) since the CM stuff is not reentrant. Is it acceptable?

**Comment by viciious** [comment]
Yes it is.

**Comment by dnk777** [comment]
Here are first (WIP, very dirty) results https://github.com/dnk777/qfusion/tree/env-sfx

Sound effects are controlled by these cvars
```
s_environment_effects (0/1)
s_environment_sampling_quality [0..1]
```

Note that these effects require the recent OpenAL Soft version because of stupid effect objects count limitation in older versions (I had to build it from sources and use LD_PRELOAD to make the library get loaded). https://openal.org/pipermail/openal/2017-February/000617.html

The most complex part is tracking of active sound sources (called «playbacks» here) from the sound frontend part (one has to update sound environment props while it is playing and the environment changes but most sounds used to be lost out of the SF sight once launched for execution).

Everything is just basic. Environment sampling could have better quality (and probably performance). Also I did not really experiment with actual effect properties available. Here is the effects manual for reference http://kcat.strangesoft.net/misc-downloads/Effects%20Extension%20Guide.pdf

**Comment by viciious** [comment]
No offense but it appears to me that you're only doing this for your own amusement without any prior consent with me on the code style and API. I do not really have time or motivation to dig through thousands of new code lines and make endless change requests.

The way I see it, here's very little chance your dubious changes will be merged. In that case, I suggest you should not create issues here and just keep working on your own fork.

**Comment by dnk777** [comment]
I have explicitly stated that this branch is experimental and is in very dirty state. There were no subjects to discuss because I was not sure whether it works at all (starting it I was clueless about how the sound module and these AL effects work, there is still a room for improvement). That post was not an invitation to a code review. I have just notified there is something that works (and now is working quite good).
