### ISSUE TITLE
Add more GLSL toon shaders

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#4]
How about including one that looks similar to Team Fortress 2 and another one like Borderland2 or something like that.

After all that seems to be a feature of qfusion, and one should build up on the strengths already there ;)

Edit: or this one: http://www.polycount.com/forum/showthread.php?t=110022

**Comment by viciious** [comment]
As of now, that's really low priority. However, if someone contributes such a shader, I'll incorporate it into the codebase of course.

**Comment by poVoq** [comment]
Ok, I will see if I can find some ;) So far I have only found a free, but Nvidia CG based version:
http://forum.unity3d.com/threads/93194-Team-Fortress-2-Toon-Shader-in-Unity-Free-Version?p=605037&viewfull=1#post605037
Would that be very difficult to convert to GLSL?

But maybe at least those premade linked "toon ramps" are of use? 

Edit: Here are some more Unity compatible code with explaination:
http://www.jonatron.ca/an-illustrative-shader-for-unity/
http://onetinyleap.wordpress.com/demos/ (scroll down for the TF2 shader code download)

**Comment by viciious** [comment]
I will look into it.

2013/6/25 poVoq notifications@github.com

> Ok, I will see if I can find some ;) So far I have only found a free, but
> Nvidia CG based version:
> 
> http://forum.unity3d.com/threads/93194-Team-Fortress-2-Toon-Shader-in-Unity-Free-Version?p=605037&viewfull=1#post605037
> Would that be very difficult to convert to GLSL?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/4#issuecomment-19933645
> .

## 

Best regards,
 Victor Luchitz

**Comment by poVoq** [comment]
Great thanks!

**Comment by mattiascibien** [comment]
I have some GLSL experience... I'll see what I can do if you wish.

**Comment by poVoq** [comment]
Awesome, extra points for implementing a dynamic deposit/dust map shader for snow etc like discussed in the now closed issue on easy GLSL for mappers (and seen here: http://www.zspline.net/blog/deposit-shader-in-mentalmill/ ) ;)

Edit: here is the issue: https://github.com/viciious/qfusion/issues/2 (if you have a good suggestion on how to implement easier shader coding by for mappers that would be great too).

**Comment by viciious** [comment]
Mattias, that'd be great. I'd start with that TF2-like shader. Seems pretty
short and straightforward to port.

2013/6/25 poVoq notifications@github.com

> Awesome, extra points for implementing a dynamic deposit/dust map shader
> for snow etc like discussed in the now closed issue on easy GLSL for
> mappers (and seen here:
> http://www.zspline.net/blog/deposit-shader-in-mentalmill/ ) ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/4#issuecomment-19976498
> .

## 

Best regards,
 Victor Luchitz

**Comment by mattiascibien** [comment]
I'll have a look. Just need to setup a testbed with Warsow :+1:

**Comment by poVoq** [comment]
Did you manage to get it running?

**Comment by mattiascibien** [comment]
Unfortunately I was not albe at the momen (my GLSL skills are for 2.0, not ES :( ) however I'll try in the next days.

**Comment by mattiascibien** [comment]
Actually today I came up with this: http://www.quake3world.com/forum/viewtopic.php?f=1&t=41283. I'll check if I can port it to GLSL for ES 2.0.

**Comment by viciious** [comment]
Shouldn't be too hard.
