### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Qfusion/qfusion#42]
I would like to point out that identifiers like "[`__TV_CMDS_H`](https://github.com/viciious/qfusion/blob/f72744d4ef06352321acdbff129a51da3e552861/source/tv_server/tv_cmds.h#L21)" and "[`__UI_DECORATORS_H__`](https://github.com/viciious/qfusion/blob/f72744d4ef06352321acdbff129a51da3e552861/source/ui/decorators/ui_decorators.h#L2)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by viciious** [comment]
Yes, provided someone submits a patch.

2013/11/28 Markus Elfring notifications@github.com

> I would like to point out that identifiers like "**TV_CMDS_Hhttps://github.com/viciious/qfusion/blob/f72744d4ef06352321acdbff129a51da3e552861/source/tv_server/tv_cmds.h#L21"
> and "__UI_DECORATORS_H**https://github.com/viciious/qfusion/blob/f72744d4ef06352321acdbff129a51da3e552861/source/ui/decorators/ui_decorators.h#L2"
> do not fithttps://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29to the expected naming convention of the C++ language standard.
> Would you like to adjust your selection for unique names?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/42
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
I’m closing this issue because it has been inactive for a while now. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with master branch. You can also contribute directly by providing a patch. :)

Thank you!

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
