### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by mikejsavage** [Qfusion/qfusion#422]
https://github.com/Qfusion/qfusion/blob/master/source/ref_gl/r_image.c#L2319

buffer overrun if any of the flip flags are true. need to allocate extra space to hold the flipped image too

(_Mem_Free: Assertion `*( (uint8_t *) mem + sizeof( memheader_t ) + mem->size ) == MEMHEADER_SENTINEL2' failed.)

https://github.com/Qfusion/qfusion/blob/master/source/cgame/cg_as_camera.cpp#L115

should be sizeof( vrect_t )

**Comment by viciious** [comment]
Thanks!
Fixed in 262de48ee7124cac501dd85f5fda52db99a6c952 and 4cc654f22a74644eb25b97d76303f0b42ee260d3
