### ISSUE TITLE
Spread bug

### ISSUE THREAD

**Issue by mikejsavage** [Qfusion/qfusion#423]
https://github.com/Qfusion/qfusion/blob/master/source/gameshared/gs_weapons.c#L47

`NormalVectorToAxis` computes some arbitrary orthonormal basis so the spread ends up getting rotated differently depending on your view angles. it should use the normal "look at" code instead

![cocainediesel_181116_201609](https://user-images.githubusercontent.com/579299/48639569-a085cb80-e9dc-11e8-9319-811387ad0a20.png)

btw there's a slick new orthonormal basis algorithm: https://graphics.pixar.com/library/OrthonormalB/paper.pdf

**Comment by viciious** [comment]
What do you mean by "the normal 'look at' code"?

**Comment by mikejsavage** [comment]
like gluLookAt. the one that takes a world up vector and aligns the new up vector with that

**Comment by viciious** [comment]
Oh well, GS_TraceBullet needs to be modified to also take either right or up vector as input parameter. The third axis can be reconstructed using CrossProduct.

**Comment by viciious** [comment]
Fixed in ec983209d554c1771db6660521976b83c256c572 and 13ea7644e12c0eadc911a7aba8314e3e805fb302
