### ISSUE TITLE
SDL atomic add doesn't behave like the others

### ISSUE THREAD

**Issue by mikejsavage** [Qfusion/qfusion#425]
Sys_Atomic_Add in sdl_threads behaves like add+fetch,

    return SDL_AtomicAdd( ( SDL_atomic_t * )value, add ) + add;

when other implementations behave like fetch+add.

Should either drop the whole file because it doesn't get used in qf, or drop the `+ add`.

**Comment by viciious** [comment]
Fixed in 7f4c150f267685e20ba0227bc211647ca843f562
Thanks!
