### ISSUE TITLE
Knockback oddities

### ISSUE THREAD

**Issue by mikejsavage** [Qfusion/qfusion#427]
**DIRECTSPLASH**:

Not sure if it's intentional but if you shoot someone above the knees with a rocket it will use the rocket direction as the knockback direction, often downwards because you are shooting at their feet so they don't go anywhere. Rockets feels very inconsistent because of this in warsow as there is a sharp cutoff between popup rockets and rockets that do nothing

https://github.com/Qfusion/qfusion/blob/master/source/game/g_weapon.cpp#L162

**VERTICALBIAS**:

There's some code to bias towards vertical kb, which is largely countered by the above

https://github.com/Qfusion/qfusion/blob/master/source/game/g_combat.cpp#L666

In CD I have removed both (and increased all vertical KB by 25%) and it feels a lot better. plasma climbing is a little odd with it but we didn't get around to tweaking that yet.

**Damage and KB have different falloff curves**:

Knockback falls off more quickly than damage. Probably the least objective issue in this list but I thought it was weird and worth highlighting. We use damage curve for knockback in CD and IMO it's better for consistency

https://github.com/Qfusion/qfusion/blob/master/source/game/g_combat.cpp#L629

**Comment by viciious** [comment]
f116d4d344ec291d757e2e5db636fe38aa10354d

**Comment by viciious** [comment]
5ca50c2
