### ISSUE TITLE
cl_maxfps clamping

### ISSUE THREAD

**Issue by mikejsavage** [Qfusion/qfusion#428]
https://github.com/Qfusion/qfusion/blob/master/source/client/cl_main.c#L2485

If you do like cl_maxfps 1 the game sets it to the literal string "absMinFps" (`"cl_maxfps" is "absMinFps" default: "250"`)

The issue is that the STR_TOSTR macro only works if its argument is a `#define`, which absMinFps isn't

**Comment by viciious** [comment]
Hehe, that's is a pretty dumb one. Thanks

**Comment by viciious** [comment]
Fixed in 3ada6c652fcf165d934129138f0bebcd13734892
