### ISSUE TITLE
Red crosshair when rewinding demos

### ISSUE THREAD

**Issue by mikejsavage** [Qfusion/qfusion#429]
If you rewind a demo the crosshair will stay red because `cg.time` gets smaller. There are some other similar HUD issues but I don't remember them

In CD I added a monotonic clock which seems reasonable to me: https://github.com/mikejsavage/forksow/commit/6698aa53d397b692f32d602b9bac13865d11b869

OTOH there are already too many clocks in qf and adding another one is not awesome

**Comment by viciious** [comment]
Isn't cg.realTime monotonic?

**Comment by mikejsavage** [comment]
yea but I wanted a clock that was monotonic across map changes (edit: for reasons that are not relevant to base qf). realTime works here too

**Comment by viciious** [comment]
> yea but I wanted a clock that was monotonic across map changes

Sys_Milliseconds()

**Comment by viciious** [comment]
The originally reported issue isn't for base qf anyway, is it? The `scr_damagetime` thing is something you added later on.

**Comment by viciious** [comment]
c385ae0828d21e02bb69c1ca832d45089b6a3a58
