### ISSUE TITLE
cmake?

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#43]
It seems that currently there three types of manually maintained projects (Visual Studio/Xcode/Makefile). Maybe it better to use something like cmake?

**Comment by viciious** [comment]
Maybe, but I'm not using *nix myself so I won't bother. MSVC projects are
no 1 priority for me.

2013/11/29 Alexey notifications@github.com

> It seems that currently there three types of manually maintained projects
> (Visual Studio/Xcode/Makefile). Maybe it better to use something like cmake?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/43
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Duplicate of issue #90
