### ISSUE TITLE
Fix FPS limiter.

### ISSUE THREAD

**Issue by ghost** [Qfusion/qfusion#436]
The current FPS limiter works only on [tickless kernels](https://en.wikipedia.org/wiki/Tickless_kernel). OpenBSD kernel is not tickless because it wants to run on as many platforms as possible, so with its default tick rate it's impossible to sleep less than 10 milliseconds.

**Comment by viciious** [comment]
a 10 milliseconds sleep is way too much for realtime applications such as games, it makes no sense to support such operating systems.

**Comment by ghost** [comment]
@viciious actually it is possible to implement FPS limiter in a different may. The author of this [code](https://gitlab.com/ftz/engine/blob/master/Src/Engine/Src/Server/EngineServer.cpp#L203) says that also makes it use less CPU, so that way all benefit.
