### ISSUE TITLE
Write FPS limiter without sleeps.

### ISSUE THREAD

**Issue by ghost** [Qfusion/qfusion#437]
I'll repeat once more: using sleep is not an appropriate way to implement FPS limiter anyway.

**Comment by ghost** [comment]
@viciious ok, I've fixed FPS limiter in my fork, is this [code](https://github.com/OrangeGrayCyan/warsow/commit/58d690e920359857f984ad1112712c0d6a7b7d8a) acceptable to you?

**Comment by ghost** [comment]
Now it limits FPS properly :P

**Comment by viciious** [comment]
No, this is not acceptable

**Comment by viciious** [comment]
The application should release the cpu resources if in idle state rather than consuming the 100% of each core, this is ridiculous

**Comment by ghost** [comment]
@viciious the ridiculous part is that Qfusion is not designed to handle different tick rates, you always assume that kernel is tickless.

**Comment by viciious** [comment]
It does not assume anything about the kernel.
Feel free to suggest a different solution which would not involve running the game at 100% cpu usage all the time

**Comment by ghost** [comment]
@viciious the funny thing is that without sleeps Warsow started using twice less CPU, isn't that weird?

**Comment by viciious** [comment]
Then you probably measure it in the wrong way
