### ISSUE TITLE
Cascaded Shadow Maps issue

### ISSUE THREAD

**Issue by GoldenThumbs** [Qfusion/qfusion#442]
They flicker and z fight on the map. If you need a screenshot of it I can grab one. Any thoughts as to what can cause this?

**Comment by viciious** [comment]
A screenshot would certainly help. But typically z-fight issues are more pronounced on slanted surfaces

**Comment by GoldenThumbs** [comment]
![Shadow Problem](https://user-images.githubusercontent.com/24837412/63814993-82001980-c8f8-11e9-8d58-708c97cae369.PNG)
It's obviously more noticeable when moving because it changes with the camera.

**Comment by viciious** [comment]
I suggest you try SM on a different map (quake1 + rtlights pack) - there's no way I can tell what's going on there by this screenshot alone. Other than that wca1 isn't the perfect choice for SM for a variety of reasons.

**Comment by GoldenThumbs** [comment]
This happens on all of Warsow's maps, did notice that Quake maps have none of these issues. Is there a problem with the BSP here?

**Comment by viciious** [comment]
One of the problems with warsow maps is aggressive caulking which f*cks up the shadowmaps by removing the capping geometry. The curved geometry may also be a problem.

**Comment by GoldenThumbs** [comment]
Ah ok. Also I did find an area in a Quake map that had the z fighting issue but I didn't screenshot it.
