### ISSUE TITLE
Input seems to be unstable with cl_sleep 1 and cl_maxfps 125-500

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#444]
**Preconditions:** 
- artifacts from https://ci.appveyor.com/project/viciious/qfusion/builds/27231132
- SDL or usual build - doesn't matter

**Case1:**

1) Start the map
2) Enable cg_showPressedKeys
3) Press & keep crouch button (+movedown)

**Result:** Screen is shaking every 2-3 seconds, crouch button indicator blinking sometimes - https://youtu.be/YXztvTGZ3Cw

**Case2:** This one is quite hard to be noticed or recorded on the video. But it's noticeable if you have high FPS and high Hz on display. 

1) Start a huge map (i.e. "depot")
2) Start jumping around the map, slowly moving mouse at the corners to perform bunny hopping

**Result:** Camera moves with little jerks sometimes, so it doesn't look smooth everytime as expected. It happens only with multiple input actions. If you just stand still and slowly move your mouse, no such issue can be reproduced.

**Important note:** Issue seems to gone with cl_maxfps 1000. It is starting to reproduce on 500 and lower cl_maxfps values. I guess it may be can connect with USB poll rate, as all my devices (mouse and keyboard) use 1000 rate.

**Comment by adem4ik** [comment]
The problem comes from cl_sleep 1. With cl_sleep 0, it can't be reproduced.

**Comment by viciious** [comment]
Should be fixed in dbc82b18ed96c5be6614c8d08515b7a617aaf37a

**Comment by adem4ik** [comment]
Yes, it feels fixed now in https://github.com/Qfusion/qfusion/commit/dbc82b18ed96c5be6614c8d08515b7a617aaf37a Both cases can't be reproduced anymore even with cl_sleep 1.
