### ISSUE TITLE
Teamcolored textures stops to work on CTF maps after 2nd map loading

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#448]
**Preconditions:** use any CTF map from Warsow/Warfork with team colored textures (i.e.
[map_wfctf2.zip](https://github.com/Qfusion/qfusion/files/3609164/map_wfctf2.zip) )

1) Start the game
2) `g_gametype "ctf"`
3) `map wfctf2` (team colored textures are working)
4) do `map wfctf2` once more (actually you can load any other CTF map here too)

**Result:** team colored textures stop to work - http://www.framecompare.com/image-compare/screenshotcomparison/D7Y67NNX

**Comment by viciious** [comment]
Fixed in 9573326ad1b8177e40a5915173aef99a9eabb56c, thanks!
