### ISSUE TITLE
Some oneshot sounds on Quake 3 maps get looped

### ISSUE THREAD

**Issue by polyzium** [Qfusion/qfusion#449]
Oneshot (ambient/global) sounds get looped on Quake 3 maps. Load up q3dm2, q3tourney3 or q3dm11 (trigger the quad trap) and listen.

(I was originally going to post videos but Streamable is blocked and GitHub doesn't allow anything higher than 10mb)

**Comment by viciious** [comment]
In the case of quad trap alert, the sound file ("sound/world/klaxon2.wav") contains a loop cue, which is respected by qfusion, but not by q3a. I'm sure it is the same with the rest.

Not a bug, really.

**Comment by polyzium** [comment]
1shot_greg_03.wav from q3dm2 for some reason contains a loop cue despite saying 1shot. WHY? You gotta make it behave like Q3A, these looping sounds will render the map mentally unplayable.

**Comment by viciious** [comment]
> 1shot_greg_03.wav from q3dm2 for some reason contains a loop cue despite saying 1shot. WHY? You gotta make it behave like Q3A, these looping sounds will render the map mentally unplayable.

Yeah, I'm going to do that but for other reasons as vq3 maps support isn't something I really care for:
- the feature has been proven to be totally useless
- the OpenAL sound module doesn't support it anyway

**Comment by Warfork** [comment]
@polyzium I tested https://github.com/Qfusion/qfusion/commit/8d337baff7d89998cfb29cfe9a6c617ac50a2d26 by @viciious and can confirm it resolves this issue.

**Comment by viciious** [comment]
Thanks
