### ISSUE TITLE
warsow 2.1 branch does not reflect warsow 2.1 sdk

### ISSUE THREAD

**Issue by Warfork** [Qfusion/qfusion#450]
I'm sure this issue will be closed, but to anyone that downloaded warsow_21_sdk.tar.gz, please be aware that this is your actual starting point: https://github.com/Qfusion/qfusion/commits/b9ea97fac227f13d5e769bff0170f08d811a2982

warsow 2.1 branch: https://github.com/Qfusion/qfusion/commits/warsow_2.1

**Comment by viciious** [comment]
> warsow 2.1 branch does not reflect warsow 2.1 sdk

The warsow_2_1_0 tag does though: https://github.com/Qfusion/qfusion/releases/tag/warsow_2_1_0

The tip of the branch may change over time.

**Comment by Warfork** [comment]
> > warsow 2.1 branch does not reflect warsow 2.1 sdk
> 
> The warsow_2_1_0 tag does though: https://github.com/Qfusion/qfusion/releases/tag/warsow_2_1_0
> 
> The tip of the branch may change over time.

Thanks.
