### ISSUE TITLE
EmitPacketEntities could be clearer

### ISSUE THREAD

**Issue by mikejsavage** [Qfusion/qfusion#454]
messing with delta coding in cd and ran into a couple things

the end packet entities marker is not written/read symmetrically in snap_write/snap_read. the game  still functions but the code is not really correct and will break if the implementation of Read/WriteEntityNum ever changes. the writer side should use WriteEntityNum instead of WriteUint16

write: https://github.com/Qfusion/qfusion/blob/master/source/qcommon/snap_write.c#L97
read: https://github.com/Qfusion/qfusion/blob/master/source/qcommon/snap_read.c#L141

also in the entity unchanged code on the reader side is kind of confusing: https://github.com/Qfusion/qfusion/blob/master/source/qcommon/snap_read.c#L159 https://github.com/Qfusion/qfusion/blob/master/source/qcommon/snap_read.c#L232

it calls SNAP_ParseDeltaEntity when no parsing occurs and all it needs to do is `new = old; newframe->numEntities++;`

**Comment by viciious** [comment]
> the writer side should use WriteEntityNum instead of WriteUint16

good point.

> it calls SNAP_ParseDeltaEntity when no parsing occurs and all it needs to do is `new = old; newframe->numEntities++;`

I'm pretty sure this is what even the original code in QuakeWorld does. I suppose it does it this way to avoid the copy and paste of the following code:

```
	state = &frame->parsedEntities[frame->numEntities & ( MAX_PARSE_ENTITIES - 1 )];
	frame->numEntities++;
        *state = *old;
```

**Comment by viciious** [comment]
dbb922c2b1045e510dc9f19cc1b9b3e201bde03e

**Comment by mikejsavage** [comment]
cool
