### ISSUE TITLE
cant build from source

### ISSUE THREAD

**Issue by The-Starflower** [Qfusion/qfusion#457]
hello i have a problem
this is my first time using this  and i dont understand this, what am i doing wrong?
here is the error
thanks 
![q](https://user-images.githubusercontent.com/60725608/73905829-54f16300-48a9-11ea-8a75-339eab6c5980.png)

**Comment by viciious** [comment]
run 'git submodule update' in the source directory or, if you're using tortoisegit, run Submodule -> Sync from the context menu

then try running cmake again
