### ISSUE TITLE
Discord server or something

### ISSUE THREAD

**Issue by HeadClot** [Qfusion/qfusion#459]
Hey would it be possible to get a discord server or something similar for discussing QFusion? 

Just curious :)

**Comment by Warfork** [comment]
You could try chatting in the Warfork discord server: https://discord.gg/VY95TKZ

Disclaimer: We have no affiliation with qfusion and merely utilize the engine.

**Comment by HeadClot** [comment]
Ok, I just joined. I am going to post a bunch of questions there about QFusion. :) 

Thank you @Warfork :)
