### ISSUE TITLE
Optional, no sound mute when window gets unfocused (Windows only?)

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#46]
Feature request:
I would like to ask for the feature which can keep ingame sound even after alt+tabbing, when game windows looses the focus. As for me, game looses the ingame sound only on Windows. On Linux Kubuntu Alt+tab doesn't work, but i can hear ingame sound even after the main window gets unfocused.

Advantages:
- It will save a lot of time and nerves for stream makers, as they can press alt+tab during streaming the match and ask/answer to the questions in the chat, watching brackets and the sites, make some other stuff without loosing gamesound on stream.
- It could be useful to hear when somebody connects to the server where you're siting and waiting for the players.

I guess it should be connected with https://github.com/viciious/qfusion/blob/master/source/win32/win_snd.c#L815

**Comment by viciious** [comment]
Use s_module 1 and s_wavonly 1

2013/12/6 Andrei Stepanov notifications@github.com

> Feature request:
> I would like to ask for the feature which can keep ingame sound even after
> alt+tabbing, when game windows looses the focus. As for me, game looses the
> ingame sound only on Windows. On Linux Kubuntu Alt+tab doesn't work, but i
> can hear ingame sound even after the main window gets unfocused.
> 
> Advantages:
> - It will save a lot of time and nerves for stream makers, as they can
>   press alt+tab during streaming the match and ask to the questions in the
>   chat, watching brackets and sites, make some other stuff without loosing
>   gamesound on stream.
> - It could be useful to hear when somebody connects to the server
>   where you're siting and waiting for the players.
> 
> I guess it should be connected with
> https://github.com/viciious/qfusion/blob/master/source/win32/win_snd.c#L815
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/46
> .

## 

Best regards,
 Victor Luchitz

**Comment by viciious** [comment]
Although it only works because of a bug I'm going to fix right now :)

2013/12/7 Victor Luchitz vluchits@gmail.com

> Use s_module 1 and s_wavonly 1
> 
> 2013/12/6 Andrei Stepanov notifications@github.com
> 
> > Feature request:
> > I would like to ask for the feature which can keep ingame sound even
> > after alt+tabbing, when game windows looses the focus. As for me, game
> > looses the ingame sound only on Windows. On Linux Kubuntu Alt+tab doesn't
> > work, but i can hear ingame sound even after the main window gets unfocused.
> > 
> > Advantages:
> > - It will save a lot of time and nerves for stream makers, as they
> >   can press alt+tab during streaming the match and ask to the questions in
> >   the chat, watching brackets and sites, make some other stuff without
> >   loosing gamesound on stream.
> > - It could be useful to hear when somebody connects to the server
> >   where you're siting and waiting for the players.
> > 
> > I guess it should be connected with
> > https://github.com/viciious/qfusion/blob/master/source/win32/win_snd.c#L815
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/46
> > .
> 
> ## 
> 
> Best regards,
>  Victor Luchitz

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
thanks for "s_wavonly 1")

**Comment by viciious** [comment]
Implemented s_globalfocus in 3d0a9ea2f23bdfb0a6f33581e3ab4619deca0364
Windows-only so far

**Comment by adem4ik** [comment]
thanks Vic

**Comment by viciious** [comment]
Completed the feature in b48bc435c85e867bfaff33204a5ed3235f555854
