### ISSUE TITLE
Libpng12 compatible version or include libpng15?

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#5]
It seems like even the current up to date Ubuntu Linux version doesn't ship with libpng15 (only libpng12) and there is no easy way to upgrade that library.

Not sure if this problem still exists with the latest source, but it certainly is a problem with the lastest Warsow release.

Would it be possible to include it in the release, or make the engine backwards compatible with libpng12?

**Comment by poVoq** [comment]
Ok just read on the forums what you will not make it compatible to lippng12.
Anyways, for reference here is how to compile and install it from source under Mint Linux 15 (e.g. Ubuntu 13.04):

first Download library (in this case libpng15)

http://sourceforge.net/projects/libpng/files/libpng15/

locate the downloaded file and extract to Downloads folder.

now go to TERMINAL and type (if you encounter any errors in the configure step resolve them by installing the needed dev packages):

cd Downloads/libpng-1.5.15

./configure --prefix=/usr/local/libpng
make check
sudo make install
make check

Congratulations you just installed the libpng

Now we need to create a shortcut and put it in /usr/lib for any program that is depended on it to work

In a new TERMINAL type:

sudo updatedb (this could take a few seconds)
locate libpng (locate the ".../libpng15.so.15" line and COPY)

now we will create a NEW LINK (shortcut) of that file to "/usr/lib/"

sudo ln -s /usr/local/libpng/lib/libpng15.so.15 /usr/lib/libpng15.so.15

you can now successfully execute applications that require libpng15.so.15 

P.S: to run Warsow you also need to follow this:
http://www.warsow.net/download/ubuntu_precise
As the Linux binaries provided in the unified release don't seem to be compatible with newer releases.

**Comment by viciious** [comment]
I could try making it downgrading our libpng version to 1.2, if that makes
some people happy :P

2013/6/24 poVoq notifications@github.com

> Ok just read on the forums what you will not make it compatible to
> lippng12.
> Anyways, for reference here is how to compile and install it from source
> under Mint Linux 15 (e.g. Ubuntu 13.04):
> 
> first Download library (in this case libpng15)
> 
> http://sourceforge.net/projects/libpng/files/libpng15/
> 
> locate the downloaded file and extract to Downloads folder.
> now go to TERMINAL and type (if you encounter any errors in the configure
> step resolve them by installing the needed dev packages):
> 
> cd Downloads/libpng-1.5.15
> 
> ./configure --prefix=/usr/local/libpng
> make check
> sudo make install
> make check
> 
> Congratulations you just installed the libpng
> 
> Now we need to create a shortcut and put it in /usr/lib for any program
> that is depended on it to work
> In a new TERMINAL type:
> 
> sudo updatedb (this could take a few seconds)
> locate libpng (locate the ".../libpng15.so.15" line and COPY)
> 
> now we will create a NEW LINK (shortcut) of that file to "/usr/lib/"
> 
> ## sudo ln -s /usr/local/libpng/lib/libpng15.so.15 /usr/lib/libpng15.so.15
> 
> you can now successfully execute applications that require libpng15.so.15
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/5#issuecomment-19919121
> .

## 

Best regards,
 Victor Luchitz
