### ISSUE TITLE
Free extraslot for WSW TV on full server

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#51]
Nowadays it usually happens that WSW TV can't connect to the full server, it is really a big problem especially when cups/turneys are going on.

Such cases can be prevented by giving free extraslot for the connected WSW TV. Lets say, server has /set sv_maxclients "8", and 8 players are already on it. WSW TV joines the server and gets 9th autoslot.

Also this move would be logical, since WSW TVs are not caunted as a player's number at in-game server browser.

**Comment by viciious** [comment]
Dunno. The actual problem is specs connecting to game servers, they should
_NOT_ be there in the first place.

**Comment by viciious** [comment]
Closing due to the lack of activity.
