### ISSUE TITLE
SDL

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#52]
Currently warsow have 3 backends: windows, os x, and X11. What do you think about making single SDL backend instead of maintaining three of them? "It would be great but I have not time for it so it's up to you" would be completely understandable :)

**Comment by viciious** [comment]
I don't mind as long as there's no loss in functionality.

2013/12/13 Alexey notifications@github.com

> Currently warsow have 3 backends: windows, os x, and X11. What do you
> think about making single SDL backend instead of maintaining three of them?
> "It would be great but I have not time for it so it's up to you" would be
> completely understandable :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/52
> .

## 

Best regards,
 Victor Luchitz

**Comment by stopiccot** [comment]
To make sure that there is no loss in functionality it would be great to remove unused functionality first. For example there is a lot joystick input related code in windows backend that has no corresponding in other backends. Is it actually used? There is also code in windows backend for handling parentWnd. Can you explain for why it is needed if needed at all?

**Comment by viciious** [comment]
The joystick code is there for historical reasons primarily although we do
get reports from people that attempt using a joystick with Warsow from time
to time: http://www.warsow.net/forum/thread/14711/1

The parentHwnd thing was originally part of my work on the firefox plugin:
http://www.warsow.net/forum/thread/14467 Basically it allows rendering to a
window handle created by another process/application.

2013/12/13 Alexey notifications@github.com

> To make sure that there is no loss in functionality it would be great to
> remove unused functionality first. For example there is a lot joystick
> input related code in windows backend that has no corresponding in other
> backends. Is it actually used? There is also code in windows backend for
> handling parentWnd. Can you explain for why it is needed if needed at all?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/52#issuecomment-30513061
> .

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
http://www.phoronix.com/scan.php?page=news_item&px=MTU2MzQ

**Comment by viciious** [comment]
Use https://wiki.libsdl.org/SDL_GL_CreateContext and friends for https://github.com/Warsow/qfusion/blob/master/source/sdl/sdl_glw.c#L266

EDIT:
Oh well, it's not possible to share a context in SDL2 without reverting to platform- or vendor- specific hacks. Pity, because this degrades loading times for SDL builds.

**Comment by stopiccot** [comment]
Actually version 2.0.2 introduced `SDL_GL_SHARE_WITH_CURRENT_CONTEXT` flag that may help. But I'm not sure what `void **surface` is so it still may be an issue.

**Comment by viciious** [comment]
Posting this link for future reference: https://bugzilla.libsdl.org/show_bug.cgi?id=2841

**Comment by viciious** [comment]
@stopiccot The surface parameter is only actually used on Android, it becomes a dummy on other platforms: https://github.com/Warsow/qfusion/blob/master/source/win32/win_glw.c#L688

**Comment by stopiccot** [comment]
Adding for reference
https://github.com/Warsow/qfusion/commit/72dc69199d527c911fd97b87f100d90c24fe89d4

**Comment by stopiccot** [comment]
Btw, besides IME support on Windows... What SDL2 related issues we have? Context sharing was fixes some time ago. But not tested ;)

**Comment by stopiccot** [comment]
What should I do to test context sharing?

**Comment by Triang3l** [comment]
I don't know, but I don't think it would be a good idea to throw away something we have full control over in favor of an opaque and generalized library.

**Comment by stopiccot** [comment]
Oh, please don't start it again. You know my position and I know yours. You simply ignore all my arguments so I don't see any point of arguing on that any more. So let's still to title of this topic and talk about any missing SDL2 bits of functionality.

**Comment by Triang3l** [comment]
The raw/DirectX input code probably, but I'm not sure if it has any effect on the gameplay.

**Comment by Triang3l** [comment]
With context sharing, you should see the textures appearing when you scroll through the models in the player options. This is easier to see if you toggle the fullbright skin in the team options, you can see the textures not being loaded for 1-2 frames.

**Comment by viciious** [comment]
We'll sure get decapitated if raw mouse input is removed from the game.

**Comment by viciious** [comment]
> What should I do to test context sharing?

What @SiPlus said but make sure you have r_multithreading set to 1 first.

**Comment by viciious** [comment]
@stopiccot http://ex60.stopiccot.com:8010/builders/Linux%20x86/builds/902/steps/shell_1/logs/stdio

**Comment by stopiccot** [comment]
Fixed on buildbot

**Comment by viciious** [comment]
Bugs: 
- Alt+enter doesn't toggle vid_fullscreen
- toggling between windowed and fullscreen mode in console produces garbled output or crashes

Both are now more-or-less fixed.

**Comment by viciious** [comment]
Window/Application icon is not set in Linux and Mac

**Comment by stopiccot** [comment]
Can't check Linux build now but Mac icon is set correctly. Here is a screenshot of current master https://www.dropbox.com/s/atsdcbbyqhznpry/Screenshot%202015-04-24%2000.33.28.png?dl=0

**Comment by stopiccot** [comment]
Do we have code for handling Alt+Enter or it is intended to be default behaviour?

**Comment by viciious** [comment]
https://github.com/Warsow/qfusion/blob/master/source/client/keys.c#L632

**Comment by viciious** [comment]
System-specific code in *_threads.c must be replaced with system-agnostic SDL threads and locking/sync primitives.

**Comment by viciious** [comment]
@stopiccot is everything still working on SDL/Mac after my changes?

**Comment by stopiccot** [comment]
It's ironic that I was pushing all this SDL2 stuff and once it got any traction I've disappeared. But I'm really busy recently. Sorry for that. About questions you asked:
- OS X build seems to be horribly broken ;) Just rubbish on the screen. I'll try to bisect later.
- I had initial SDL based threads implementation but I remember having some issues so it's not finished. Anyway i'll try to find it and push it as-is so it can be a foundation to further work.

**Comment by viciious** [comment]
Well, after giving it a second thought, we don't really need SDL threads as we don't want to link the dedicated server binary against SDL.

**Comment by stopiccot** [comment]
Anyway I've pushed it already. As far as I remember SDL is missing "just_kill_that_thread" function for some reason.

**Comment by stopiccot** [comment]
Anyway it can be refactored to use some flags so thread just exits itself without being forcibly stopped.

**Comment by viciious** [comment]
> Anyway it can be refactored to use some flags so thread just exits itself without being forcibly stopped.

No, you can't do that with an arbitrary thread or a thread that is blocked by I/O or DNS query.

**Comment by Triang3l** [comment]
Condition variables are not implemented in SDL on Windows, by the way.

**Comment by viciious** [comment]
How so? https://wiki.libsdl.org/SDL_CreateCond?highlight=%28\bCategoryAPI\b%29|%28SDLFunctionTemplate%29

**Comment by Triang3l** [comment]
https://hg.libsdl.org/SDL/file/e0e2e94ce5ea/src/thread/windows - there's no SDL_syscond.c here.

**Comment by viciious** [comment]
https://hg.libsdl.org/SDL/file/e0e2e94ce5ea/src/thread/generic/SDL_syscond.c

**Comment by viciious** [comment]
Closing. Any outstanding issues will be handled in separate issues.
