### ISSUE TITLE
Rendering without non-power-of-two texture is broken

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#53]
Rendering without texture_non_power_of_two forced is broken and gives such result (running 1280x800 windowed):

![screenshot](https://f.cloud.github.com/assets/24836/1796001/c5355a42-6a4b-11e3-8262-1a855ef146af.png)

Maybe instead of fixing bug texture_non_power_of_two extension should be made obligatory  and thats it. But as far as I know there is no support for non power of two textures in OpenGL ES 2.0 and there is also an old hack (still actual?) that forces them to be disabled on OS X (r_register.c line 634).

**Comment by stopiccot** [comment]
It seems that I was wrong and only OpenGL ES 1.1 does not support npot textures. OpenGL ES 2.0 support them but with some limitations.

**Comment by viciious** [comment]
Thanks for reporting the issue. I will fix it in the follow up commit.

**Comment by viciious** [comment]
Fixed in 576f8d05809b3ed41620cb89e679eb13cc4caa2b
