### ISSUE TITLE
Where to get gamefiles for testing qfusion?

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#55]
Running with gamefiles from Warsow 1.03 makes main menu unusable due to latest angelscript/ui related changes.

**Comment by viciious** [comment]
http://gitlab.picmip.org/basewsw.zip

**Comment by adem4ik** [comment]
thanks!

**Comment by stopiccot** [comment]
yet again, running qfusion 24f7d1f250239cf2ea9aba1fc71ab537c17f2e5e with warsow 1.5 gamefiles gives such result:

![2014-05-04 19 09 03](https://cloud.githubusercontent.com/assets/24836/2873401/eeebfe62-d3a6-11e3-9e77-22c349f8f52e.png)

**Comment by stopiccot** [comment]
it would be great to have tag on some revision saying "this works with warsow 1.5 gamefiles"

**Comment by Triang3l** [comment]
You need to copy the `glsl` folder from this repo to `basewsw`.
