### ISSUE TITLE
Incomplete compile of the latest qfusion

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#56]
I've got following message during compile of the latest qfusion on Kubuntu 13.04:

make: **\* Нет правила для сборки цели `buildx86_64/ui/ui_parsersound.o', требуемой для`compile-ui'.  Останов.
adem@adem4ik:~/qfusion/source$ 

which means "There is no rule to make the target  'buildx86_64/ui/ui_parsersound.o', which is needed for `compile-ui'. Stopping."

As I noticed there is only a few compiled libs in "qfusion/source/release/libs/":
snd_qf_x86_64.so
snd_openal_x86_64.so

So in result Warsow doesn't want to start with those bins :/
Here is a full log from console - http://yadi.sk/d/lk9YssHBFA64u

**Comment by viciious** [comment]
Try now.

2013/12/29 Andrei Stepanov notifications@github.com

> I've got following message during compile of the latest qfusion on Kubuntu
> 13.04:
> 
> make: **\* Нет правила для сборки цели buildx86_64/ui/ui_parsersound.o',
> требуемой дляcompile-ui'. Останов.
> adem@adem4ik:~/qfusion/source$
> 
> which means "There is no rule to make the target
> 'buildx86_64/ui/ui_parsersound.o', which is needed for `compile-ui'.
> Stopping."
> 
> As I noticed there is only a few compiled libs in
> "qfusion/source/release/libs/":
> snd_qf_x86_64.so
> snd_openal_x86_64.so
> 
> So in result Warsow doesn't want to start with those bins :/
> Here is a full log from console - http://yadi.sk/d/lk9YssHBFA64u
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/56
> .

## 

Best regards,
 Victor Luchitz

**Comment by adem4ik** [comment]
yes, everything seems fine now
