### ISSUE TITLE
Webserver side code?

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#6]
Maybe I am overlooking things (or is that the second branch?), but where is actually the webserver side code for the player stats and friendlists etc?
I hope it is not kept close source, as that is really one of the main features that sets qfusion apart from other idTech based engines.

**Comment by viciious** [comment]
It is closed source

2013/6/25 poVoq notifications@github.com

> Maybe I am overlooking things (or is that the second branch?), but where
> is actually the webserver side code for the player stats and friendlists
> etc?
> I hope it is not kept close source, as that is really one of the main
> features that sets qfusion apart from other idTech based engines.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/6
> .

## 

Best regards,
 Victor Luchitz

**Comment by poVoq** [comment]
Ahh that is too bad. No chance that at least the general framework could be released also? If some-one was to make a new open-source multiplayer game based on qfusion (which I am currently contemplating) that would be a really vital feature (e.g. the one that makes me most interested in it, besides the nice scripting features).

Otherwise, how difficult would it be to re-implement that server side code from scratch (e.g. does it depend mostly on easy to extend standard webserver programs)?

**Comment by viciious** [comment]
Guess we gonna opensource it after all, stay tuned.

2013/6/25 poVoq notifications@github.com

> Ahh that is too bad. No chance that at least the general framework could
> be released also? If some-one was to make a new open-source multiplayer
> game based on qfusion (which I am currently contemplating) that would be a
> really vital feature (e.g. the one that makes me most interested in it,
> besides the nice scripting features).
> 
> Otherwise, how difficult would it be to re-implement that server side code
> from scratch (e.g. does it depend mostly on easy to extend standard
> webserver programs)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/6#issuecomment-19970934
> .

## 

Best regards,
 Victor Luchitz

**Comment by poVoq** [comment]
Awesome news! Thanks a lot.

**Comment by viciious** [comment]
https://github.com/viciious/qfusion/tree/master/tools/warmama-4.0
