### ISSUE TITLE
MM Login while connected

### ISSUE THREAD

**Issue by kalhartt** [Qfusion/qfusion#82]
You can't login while connected to a server. This looks intentional, maybe as a security measure? I think it would be useful to allow logging in when already connected. Mainly because I'm worried about sessions timing out when playing for hours on a server across many maps, haven't been able to test due to my other login issues so far :D. Thoughts?

**Comment by viciious** [comment]
For this to become reality you'll have to come up with design/API changes yourself. At the moment, session id is transmitted to the server at the connection stage and thus can not change after that.

**Comment by kalhartt** [comment]
My thought was along these lines.
- client mm queries would be disconnected from the gameserver connecting process
- game module would provide a comand like `g_mm_login csession cticket`
- after connecting, client would automatically query /ccc and execute command on callback

Which is essentially what racesow was using before, of course there would need to be some extras in the game command like flood protection and clearing player stats.

**Comment by viciious** [comment]
What you're proposing won't work unless I'm connected to a game server.
This is a major flaw.

2014-04-30 2:20 GMT+04:00 Kalhartt notifications@github.com:

> My thought was along these lines.
> - client mm queries would be disconnected from the gameserver
>   connecting process
> - game module would provide a comand like g_mm_login csession cticket
> - after connecting, client would automatically query /ccc and execute
>   command on callback
> 
> Which is essentially what racesow was using before, of course there would
> need to be some extras in the game command like flood protection and
> clearing player stats.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viciious/qfusion/issues/82#issuecomment-41739556
> .

## 

Best regards,
 Victor Luchitz

**Comment by kalhartt** [comment]
The only part of this that must be done on a gameserver is obtaining a ticket_id (which at the moment must be done while connecting to a gameserver). The /clogin query to get session_id and profile info is unchanged.

**Comment by viciious** [comment]
I still think we don't want users to manually issue console commands. Any thoughts on how we could handle this automatically?

**Comment by kalhartt** [comment]
Right of course, we just have the /ccc query auto-execute in some post-connect hook. This could be done purely clientside.
In racesow, we had the game module send a client command on 'entergame' which made the client respond w/ the login command as a workaround for not being able to modify client.

**Comment by Triang3l** [comment]
How about simply asking the player to reconnect after logging in while playing on a ranked server?

**Comment by viciious** [comment]
Closing due to the lack of activity.
