### ISSUE TITLE
Load renderer resources in a separate thread

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#94]
When resource registration is over (R_EndRegistration call), all futher resources should be loaded in a separate thread to prevent hitches during the gameplay.

The R_Register\* calls would still return a valid resource handle, internally marked as 'loaded'. volatile qboolean/int loaded needs to be added to shader_t, model_t and glsl_program_t;

The frontend would issue commands to the loader thread using the same mechanics/queue as used in the sound modules.

Mutexes/critical sections need to be added to R_LoadImage/R_FindImage, R_FreeImage, R_LoadShader, R_UnlinkShader, R_RegisterProgram, RP_RegisterProgram, R_CreateMeshVBO, R_ReleaseMeshVBO, possibly other functions too. Global variables would need to be eliminated as much as possible.

The backend will simply skip rendering meshes for unloaded resources. For GLSL programs we could instead fallback to most basic permutation of the same type, which is guaranteed to exit and be loaded.

**Comment by viciious** [comment]
The loader thread would need to create its own GL context and share GL display lists with the main thread/context either via wglShareLists (Win32) or pass the main context as parameter to glXCreateContext (X11).

**Comment by Triang3l** [comment]
-shit removed-

**Comment by viciious** [comment]
No I won't end up with "invisible player shooting out of nowhere". Loading a model takes 300-500 msec in the worst case and mostly happens at the time a player joins the game. Chances anything would be missing are miniscule.
I could defer the actual loading like q3a does but that's so 90's that I won't bother.

**Comment by viciious** [comment]
Done to a certain degree: 
- textures can now be loaded in a separate thread
- added r_multithreading cvar (turned off by default)
